id: 90000006
key: "xilonen"
rarity: QUALITY_ORANGE
body: BODY_LADY
region: ASSOC_TYPE_NATLAN
element: Rock
weapon_class: WEAPON_SWORD_ONE_HAND
icon_name: "UI_AvatarIcon_Ambor"
stats: {
   base_hp: 966
   base_atk: 21
   base_def: 72
   hp_curve: GROW_CURVE_HP_S5
   atk_curve: GROW_CURVE_ATTACK_S5
   def_cruve: GROW_CURVE_HP_S5
   promo_data: {
      max_level: 20
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
      }
      add_props: {
         prop_type: FIGHT_PROP_DEFENSE_PERCENT
      }
   }
   promo_data: {
      max_level: 40
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 828
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 62
      }
      add_props: {
         prop_type: FIGHT_PROP_DEFENSE_PERCENT
         value: 18
      }
      add_props: {
         prop_type: FIGHT_PROP_DEFENSE_PERCENT
      }
   }
   promo_data: {
      max_level: 50
add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1416.294
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 106.051
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 30.789
      }
      add_props: {
         prop_type: FIGHT_PROP_DEFENSE_PERCENT
         value: 0.09
      }
   }
   promo_data: {
      max_level: 60
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2200.7412
      }
add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 164.7898
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 47.8422
      }
      add_props: {
         prop_type: FIGHT_PROP_DEFENSE_PERCENT
         value: 0.18
      }
   }
   promo_data: {
      max_level: 70
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2789.0352
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 208.8408
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 60.6312
      }
      add_props: {
         prop_type: FIGHT_PROP_DEFENSE_PERCENT
         value: 0.18
      }
   }
   promo_data: {
      max_level: 80
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3377.3292
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 252.8918
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 73.4202
      }
      add_props: {
         prop_type: FIGHT_PROP_DEFENSE_PERCENT
         value: 0.27
      }
   }
   promo_data: {
      max_level: 90
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3965.706
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 296.949
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 86.211
      }
      add_props: {
         prop_type: FIGHT_PROP_DEFENSE_PERCENT
         value: 0.36
      }
   }
}
skill_details: {
   skill: 10262
   burst: 10265
   attack: 10261
   burst_energy_cost: 60
}
name_text_hash_map: 1021947691