package_name: clorinde
genshin_id: 90000001
key: clorinde
action_param_keys:
    skill: 
        - param: "illusion_delay"
    low_plunge:
        - param: "collision"
    high_plunge:
        - param: "collision"
skill_data_mapping:
    attack:
        attack_1:
            - 0 # 1-Hit DMG|{param0:F1P}
        attack_2:
            - 1 # 2-Hit DMG|{param1:F1P}
        attack_3:
            - 2 # 3-Hit DMG|{param2:F1P}
            - 2 # 3-Hit DMG|{param2:F1P}
        attack_4:
            - 3 # 4-Hit DMG|{param3:F1P}×2
            - 3 # 4-Hit DMG|{param3:F1P}×2
            - 3 # 4-Hit DMG|{param3:F1P}×2
        attack_5:
            - 4 # 5-Hit DMG|{param4:F1P}
        ca:
            - 5 # Charged Attack DMG|{param5:F1P}
        collision:
            - 6 # Plunge DMG|{param6:F1P}
        lowPlunge:
            - 7 # Low/High Plunge DMG|{param7:P}/{param8:P}
        highPlunge:
            - 8 # Low/High Plunge DMG|{param7:P}/{param8:P}
    skill:
        swift:
            - 0 # Swift Hunt DMG (>100% BoL)|{param0:F1P}
            - 1 # Swift Hunt DMG (<100% BoL)|{param1:F1P}
        impale:
            - 2 # Impale the Night DMG(0% BoL)|{param2:F1P}
            - 3 # Impale the Night DMG(<100% BoL)|{param2:F1P}
            - 4 # Impale the Night DMG(>100% BoL)|{param2:F1P}
        arkhe:
            - 5 # Surging Blade DMG|{param5:F1P}
    burst:
        burst:
            - 0 # Skill DMG DMG|{param0:F1P}
        burstbol:
            - 1 # Bond of Life Gain|{param1:F1P}
