id: 90000001
key: "clorinde"
rarity: QUALITY_ORANGE
body: BODY_LADY
region: ASSOC_TYPE_FONTAINE
element: Electric
weapon_class: WEAPON_SWORD_ONE_HAND
icon_name: "UI_AvatarIcon_Ambor"
stats: {
   base_hp: 1009
   base_atk: 26
   base_def: 61
   hp_curve: GROW_CURVE_HP_S5
   atk_curve: GROW_CURVE_ATTACK_S5
   def_cruve: GROW_CURVE_HP_S5
   promo_data: {
      max_level: 20
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
      }
   }
   promo_data: {
      max_level: 40
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1009
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 61
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 26
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
      }
   }
   promo_data: {
      max_level: 50
add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1725.92105263158
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 104.342105263158
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 44.4736842105263
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.048
      }
   }
   promo_data: {
      max_level: 60
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2681.81578947368
      }
add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 162.131578947368
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 69.1052631578947
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.096
      }
   }
   promo_data: {
      max_level: 70
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3398.73648941276
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 205.473662888185
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 87.5789382802098
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.096
      }
   }
   promo_data: {
      max_level: 80
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 4115.65771839059
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 248.815778812513
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 106.052627034842
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.144
      }
   }
   promo_data: {
      max_level: 90
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 4832.57894736842
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 292.157894736842
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 124.526315789474
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.192
      }
   }
}
skill_details: {
   skill: 10262
   burst: 10265
   attack: 10261
   burst_energy_cost: 60
}
name_text_hash_map: 1021947691