package_name: varesa
genshin_id: 90000551
key: varesa
action_param_keys:
  attack:
    - param: "travel"
  burst:
    - param: "travel"
skill_data_mapping:
  attack:
    attack_1:
      - 0 # 1-Hit DMG|{param0:F1P}
    attack_2:
      - 1 # 2-Hit DMG|{param1:F1P}
    attack_3:
      - 2 # 3-Hit DMG|{param2:F1P}
    attack_1fp:
      - 3 # 1-Hit DMG (Fiery Passion)|{param3:F1P}
    attack_2fp:
      - 4 # 2-Hit DMG (Fiery Passion)|{param4:F1P}
    attack_3fp:
      - 5 # 3-Hit DMG (Fiery Passion)|{param5:F1P}
    charge:
      - 6 # Charged Attack DMG|{param6:F1P}
    charge:
      - 7 # Charged Attack DMG|{param7:F1P}
    collision:
      - 15 # Plunge DMG|{param15:F1P}
    lowPlunge:
      - 16 # Low/High Plunge DMG|{param16:P}/{param16:P}
    highPlunge:
      - 17 # Low/High Plunge DMG|{param17:P}/{param17:P}
    lowPlunge:
      - 18 # Low/High Plunge DMG (Fiery Passion)|{param16:P}/{param16:P}
    highPlunge:
      - 19 # Low/High Plunge DMG (Fiery Passion)|{param17:P}/{param17:P}
  skill:
    skill:
      - 0 # |{param0:F1P}
    skillfp:
      - 1 # |{param1:F1P}
  burst:
    burst:
      - 0 # |{param0:F1P}
    burstfp:
    - 1 # |{param1:F1P}
    volcano:
    - 0 # |{param2:F1P}