id: 90000551
key: "varesa"
rarity: QUALITY_ORANGE
body: BODY_GIRL
region: ASSOC_TYPE_NATLAN
element: Electric
weapon_class: WEAPON_CATALYST
icon_name: "UI_AvatarIcon_Ambor"
stats: {
   base_hp: 989
   base_atk: 28
   base_def: 61
   hp_curve: GROW_CURVE_HP_S5
   atk_curve: GROW_CURVE_ATTACK_S5
   def_cruve: GROW_CURVE_HP_S5
   promo_data: {
      max_level: 20
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
      }
   }
   promo_data: {
      max_level: 40
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 870
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 52
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 24
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
      }
   }
   promo_data: {
      max_level: 50
add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1488.135
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 88.946
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 41.052
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.048
      }
   }
   promo_data: {
      max_level: 60
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2312.373
      }
add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 138.2108
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 63.7896
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.096
      }
   }
   promo_data: {
      max_level: 70
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2930.508
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 175.1568
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 80.8416
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.096
      }
   }
   promo_data: {
      max_level: 80
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3548.643
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 212.1028
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 97.8936
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.144
      }
   }
   promo_data: {
      max_level: 90
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 4166.865
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 249.054
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 114.948
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.192
      }
   }
}
skill_details: {
   skill: 10262
   burst: 10265
   attack: 10261
   burst_energy_cost: 70
}
name_text_hash_map: 1021947691