// Code generated by "pipeline"; DO NOT EDIT.
package flins

import (
	_ "embed"

	"fmt"
	"slices"

	"github.com/genshinsim/gcsim/pkg/core/action"
	"github.com/genshinsim/gcsim/pkg/core/keys"
	"github.com/genshinsim/gcsim/pkg/gcs/validation"
	"github.com/genshinsim/gcsim/pkg/model"
	"google.golang.org/protobuf/encoding/prototext"
)

//go:embed data_gen.textproto
var pbData []byte
var base *model.AvatarData
var paramKeysValidation = map[action.Action][]string{
	5: {"collision"},
	6: {"collision"},
}

func init() {
	base = &model.AvatarData{}
	err := prototext.Unmarshal(pbData, base)
	if err != nil {
		panic(err)
	}
	validation.RegisterCharParamValidationFunc(keys.Flins, ValidateParamKeys)
}

func ValidateParamKeys(a action.Action, keys []string) error {
	valid, ok := paramKeysValidation[a]
	if !ok {
		return nil
	}
	for _, v := range keys {
		if !slices.Contains(valid, v) {
			return fmt.Errorf("key %v is invalid for action %v", v, a.String())
		}
	}
	return nil
}

func (x *char) Data() *model.AvatarData {
	return base
}

var (
	attack = [][][]float64{
		{attack_1},
		{attack_2},
		{attack_3},
		attack_4,
		{attack_5},
	}
	attack_e = [][][]float64{
		{attack_e_1},
		{attack_e_2},
		{attack_e_3},
		attack_e_4,
		{attack_e_5},
	}
)

/* ADDITIONAL INSTRUCTION FOR COPILOT
EXAMPLE:
	// attack: attack_1 = [0] ---- [ability]: [ability internal name] = [ability index, must be consistent with config.yml]
	// Pocztowy Demonspear: 1-Hit DMG ---- [real talent name]: [ability in the talent]
	attack_1 = []float64{
		0.348,   ---- talent level 1, number in the wiki is written by percentage, so convert it to decimal
		0.376188,   ---- talent level 2
		0.404724,   ---- talent level 3 ... and so on
		0.445092,
		0.47328,
		0.505644,
		0.550188,
		0.594732,
		0.639276,
		0.687996,
		0.736368,
		0.785088,
		0.83346, ---- talent scaling must have 15 levels, but some ability only have 11 or 13 levels, so just repeat the last value
		0.83346,
		0.83346,
	}

all value should be taken from https://wiki.hoyolab.com/pc/genshin/entry/8398?lang=en-us.
*/

var (
	// attack: attack_1 = [0]
	// Pocztowy Demonspear: 1-Hit DMG
	attack_1 = []float64{}
	// attack: attack_2 = [1]
	// Pocztowy Demonspear: 2-Hit DMG
	attack_2 = []float64{}
	// attack: attack_3 = [2]
	// Pocztowy Demonspear: 3-Hit DMG
	attack_3 = []float64{}
	// attack: attack_4 = [3 4]
	// Pocztowy Demonspear: 4-Hit DMG
	attack_4 = [][]float64{
		{},
		{},
	}
	// attack: attack_5 = [5]
	// Pocztowy Demonspear: 5-Hit DMG
	attack_5 = []float64{}
	// attack: charge = [6]
	// Pocztowy Demonspear: Charged Attack DMG
	charge = []float64{}
	// attack: collision = [6]
	// Pocztowy Demonspear: Plunge DMG
	collision = []float64{}
	// attack: highPlunge = [8]
	// Pocztowy Demonspear: High Plunge DMG
	highPlunge = []float64{}
	// attack: lowPlunge = [7]
	// Pocztowy Demonspear: Low Plunge DMG
	lowPlunge = []float64{}
	// skill: attack_e_1 = [0]
	// Ancient Rite: Arcane Light: 1-Hit DMG
	attack_e_1 = []float64{}
	// skill: attack_e_2 = [1]
	// Ancient Rite: Arcane Light: 2-Hit DMG
	attack_e_2 = []float64{}
	// skill: attack_e_3 = [2]
	// Ancient Rite: Arcane Light: 3-Hit DMG
	attack_e_3 = []float64{}
	// skill: attack_e_4 = [3 4]
	// Ancient Rite: Arcane Light: 4-Hit DMG
	attack_e_4 = [][]float64{
		{},
		{},
	}
	// skill: attack_e_5 = [5]
	// Ancient Rite: Arcane Light: 5-Hit DMG
	attack_e_5 = []float64{}
	// skill: charge_e = [6]
	// Ancient Rite: Arcane Light: Charged Attack DMG
	charge_e = []float64{}
	// skill: skill = [7]
	// Ancient Rite: Arcane Light: Northland Spearstorm DMG
	skill = []float64{}
	// burst: burst = [0]
	// Ancient Ritual: Cometh the Night: Initial Skill DMG
	burst = []float64{}
	// burst: burstlcmid = [1]
	// Ancient Ritual: Cometh the Night: Middle Phase Lunar-Charged DMG
	burstlcmid = []float64{}
	// burst: burstlcfin = [2]
	// Ancient Ritual: Cometh the Night: Final Phase Lunar-Charged DMG
	burstlcfin = []float64{}
	// burst: burstlcts = [3]
	// Ancient Ritual: Cometh the Night: Thunderous Symphony DMG
	burstlcts = []float64{}
	// burst: burstlctsadd = [4]
	// Ancient Ritual: Cometh the Night: Thunderous Symphony Additional DMG
	burstlctsadd = []float64{}
)
