// Code generated by "pipeline"; DO NOT EDIT.
package columbina

import (
	_ "embed"

	"fmt"
	"slices"

	"github.com/Karashina/gcsim-unofficial-clone/pkg/core/action"
	"github.com/Karashina/gcsim-unofficial-clone/pkg/core/keys"
	"github.com/Karashina/gcsim-unofficial-clone/pkg/gcs/validation"
	"github.com/Karashina/gcsim-unofficial-clone/pkg/model"
	"google.golang.org/protobuf/encoding/prototext"
)

//go:embed data_gen.textproto
var pbData []byte
var base *model.AvatarData
var paramKeysValidation = map[action.Action][]string{
	5: {"collision"},
	6: {"collision"},
}

func init() {
	base = &model.AvatarData{}
	err := prototext.Unmarshal(pbData, base)
	if err != nil {
		panic(err)
	}
	validation.RegisterCharParamValidationFunc(keys.Columbina, ValidateParamKeys)
}

func ValidateParamKeys(a action.Action, keys []string) error {
	valid, ok := paramKeysValidation[a]
	if !ok {
		return nil
	}
	for _, v := range keys {
		if !slices.Contains(valid, v) {
			return fmt.Errorf("key %v is invalid for action %v", v, a.String())
		}
	}
	return nil
}

func (x *char) Data() *model.AvatarData { return base }

// Talent scaling tables (from newchar.md)
var (
	// Normal Attack scaling (15 entries each)
	attack = [][][]float64{{attack_1}, {attack_2}, {attack_3}}

	attack_1 = []float64{0.468, 0.503, 0.538, 0.585, 0.620, 0.655, 0.702, 0.749, 0.795, 0.842, 0.889, 0.936, 0.936, 0.936, 0.936}
	attack_2 = []float64{0.366, 0.394, 0.421, 0.458, 0.485, 0.513, 0.549, 0.586, 0.623, 0.659, 0.696, 0.733, 0.733, 0.733, 0.733}
	attack_3 = []float64{0.585, 0.629, 0.673, 0.731, 0.775, 0.819, 0.877, 0.936, 0.994, 1.053, 1.111, 1.170, 1.170, 1.170, 1.170}

	// Charged Attack scaling (15 entries)
	charge = []float64{1.161, 1.248, 1.335, 1.451, 1.538, 1.625, 1.741, 1.857, 1.973, 2.089, 2.206, 2.322, 2.322, 2.322, 2.322}

	// Moondew Cleanse (Max HP % x3, 15 entries)
	moondewCleanse = []float64{0.0151, 0.0162, 0.0174, 0.0189, 0.0200, 0.0212, 0.0227, 0.0242, 0.0257, 0.0272, 0.0287, 0.0302, 0.0302, 0.0302, 0.0302}

	// Plunge Attack scaling (15 entries)
	collision  = []float64{0.568, 0.615, 0.661, 0.727, 0.773, 0.826, 0.899, 0.971, 1.044, 1.123, 1.203, 1.282, 1.282, 1.282, 1.282}
	lowPlunge  = []float64{1.14, 1.23, 1.32, 1.45, 1.55, 1.65, 1.80, 1.94, 2.09, 2.25, 2.40, 2.56, 2.56, 2.56, 2.56}
	highPlunge = []float64{1.42, 1.53, 1.65, 1.82, 1.93, 2.06, 2.24, 2.43, 2.61, 2.81, 3.00, 3.20, 3.20, 3.20, 3.20}

	// Elemental Skill - Eternal Tides (Max HP %, 15 entries)
	skillDmg = []float64{0.167, 0.180, 0.192, 0.209, 0.222, 0.234, 0.251, 0.268, 0.284, 0.301, 0.318, 0.334, 0.355, 0.355, 0.355}

	// Gravity Ripple: Continuous DMG (Max HP %, 15 entries)
	gravityRippleDmg = []float64{0.094, 0.101, 0.108, 0.117, 0.124, 0.131, 0.140, 0.150, 0.159, 0.168, 0.178, 0.187, 0.199, 0.199, 0.199}

	// Gravity Interference: Lunar-Charged DMG (Max HP %, 15 entries)
	gravityInterfLC = []float64{0.0470, 0.0506, 0.0541, 0.0588, 0.0623, 0.0659, 0.0706, 0.0753, 0.0800, 0.0847, 0.0894, 0.0941, 0.1000, 0.1000, 0.1000}

	// Gravity Interference: Lunar-Bloom DMG (Max HP % x5, 15 entries)
	gravityInterfLB = []float64{0.0141, 0.0151, 0.0162, 0.0176, 0.0187, 0.0197, 0.0211, 0.0225, 0.0239, 0.0253, 0.0268, 0.0282, 0.0299, 0.0299, 0.0299}

	// Gravity Interference: Lunar-Crystallize DMG (Max HP %, 15 entries)
	gravityInterfLCrs = []float64{0.0882, 0.0949, 0.1015, 0.1103, 0.1169, 0.1235, 0.1324, 0.1412, 0.1500, 0.1588, 0.1677, 0.1765, 0.1875, 0.1875, 0.1875}

	// Elemental Burst - Moonlit Melancholy (Max HP %, 15 entries)
	burstDmg = []float64{0.322, 0.347, 0.371, 0.403, 0.427, 0.451, 0.484, 0.516, 0.548, 0.580, 0.613, 0.645, 0.685, 0.685, 0.685}

	// Lunar Reaction DMG Bonus (15 entries)
	burstBonus = []float64{0.13, 0.16, 0.19, 0.22, 0.25, 0.28, 0.31, 0.34, 0.37, 0.40, 0.43, 0.46, 0.49, 0.49, 0.49}
)

const normalHitNum = 3
