// Code generated by "pipeline"; DO NOT EDIT.
package citlali

import (
	_ "embed"

	"fmt"
	"github.com/genshinsim/gcsim/pkg/core/action"
	"github.com/genshinsim/gcsim/pkg/core/keys"
	"github.com/genshinsim/gcsim/pkg/gcs/validation"
	"github.com/genshinsim/gcsim/pkg/model"
	"google.golang.org/protobuf/encoding/prototext"
	"slices"
)

//go:embed data_gen.textproto
var pbData []byte
var base *model.AvatarData
var paramKeysValidation = map[action.Action][]string{
	3: {"travel"},
	4: {"travel"},
}

func init() {
	base = &model.AvatarData{}
	err := prototext.Unmarshal(pbData, base)
	if err != nil {
		panic(err)
	}
	validation.RegisterCharParamValidationFunc(keys.Citlali, ValidateParamKeys)
}

func ValidateParamKeys(a action.Action, keys []string) error {
	valid, ok := paramKeysValidation[a]
	if !ok {
		return nil
	}
	for _, v := range keys {
		if !slices.Contains(valid, v) {
			return fmt.Errorf("key %v is invalid for action %v", v, a.String())
		}
	}
	return nil
}

func (x *char) Data() *model.AvatarData {
	return base
}

var (
	attack = [][]float64{
		attack_1,
		attack_2,
		attack_3,
	}
)

var (
	// attack: attack_1 = [0]
	attack_1 = []float64{
		0.434,
		0.46655,
		0.4991,
		0.5425,
		0.57505,
		0.6076,
		0.651,
		0.6944,
		0.7378,
		0.7812,
		0.8246,
		0.868,
		0.92225,
		0.92225,
		0.92225,		
	}
	// attack: attack_2 = [1]
	attack_2 = []float64{
		0.388,
		0.4171,
		0.4462,
		0.485,
		0.5141,
		0.5432,
		0.582,
		0.6208,
		0.6596,
		0.6984,
		0.7372,
		0.776,
		0.8245,
		0.8245,
		0.8245,		
	}
	// attack: attack_3 = [2]
	attack_3 = []float64{
		0.538,
		0.57835,
		0.6187,
		0.6725,
		0.71285,
		0.7532,
		0.807,
		0.8608,
		0.9146,
		0.9684,
		1.0222,
		1.076,
		1.14325,
		1.14325,
		1.14325,		
	}
	// attack: charge = [3]
	charge = []float64{
		0.992,
		1.0664,
		1.1408,
		1.24,
		1.3144,
		1.3888,
		1.488,
		1.5872,
		1.6864,
		1.7856,
		1.8848,
		1.984,
		2.108,
		2.108,
		2.108,		
	}
	// skill: skill = [0]
	skill = []float64{
		0.73,
		0.78475,
		0.8395,
		0.9125,
		0.96725,
		1.022,
		1.095,
		1.168,
		1.241,
		1.314,
		1.387,
		1.46,
		1.55125,
		1.55125,
		1.55125,		
	}
	// skill: shieldperct = [1]
	shieldperct = []float64{
		5.76,
		6.192,
		6.624,
		7.2,
		7.632,
		8.064,
		8.64,
		9.216,
		9.792,
		10.368,
		10.944,
		11.52,
		12.24,
		12.24,
		12.24,		
	}
	// skill: shieldconst = [2]
	shieldconst = []float64{
		1387,
		1525.7,
		1675.496,
		1837.775,
		2011.15,
		2195.621,
		2392.575,
		2600.625,
		2819.771,
		3051.4,
		3294.125,
		3549.333,
		3814.25,
		3814.25,
		3814.25,		
	}
	// skill: skilldot = [3]
	skilldot = []float64{
		0.17,
		0.18275,
		0.1955,
		0.2125,
		0.22525,
		0.238,
		0.255,
		0.272,
		0.289,
		0.306,
		0.323,
		0.34,
		0.36125,
		0.36125,
		0.36125,		
	}
	// burst: burst = [0]
	burst = []float64{
		5.376,
		5.7792,
		6.1824,
		6.72,
		7.1232,
		7.5264,
		8.064,
		8.6016,
		9.1392,
		9.6768,
		10.2144,
		10.752,
		11.424,
		11.424,
		11.424,		
	}
	// burst: burstskull = [1]
	burstskull = []float64{
		1.344,
		1.4448,
		1.5456,
		1.68,
		1.7808,
		1.8816,
		2.016,
		2.1504,
		2.2848,
		2.4192,
		2.5536,
		2.688,
		2.856,
		2.856,
		2.856,				
	}
)
