package_name: citlali
genshin_id: 90000005
key: citlali
action_param_keys:
  attack:
    - param: "travel"
  charge:
    - param: "travel"
skill_data_mapping:
  attack:
    attack_1:
      - 0 # 1-Hit DMG|{param0:F1P}
    attack_2:
      - 1 # 2-Hit DMG|{param1:F1P}
    attack_3:
      - 2 # 3-Hit DMG|{param2:F1P}
    charge:
      - 3 # Charged Attack DMG|{param3:F1P}
  skill:
    skill:
      - 0 # Obsidian Tzitzimitl DMG|{param0:F1P}
    shieldperct:
      - 1 # Shield DMG Absorption|{param1:F1P} EM
    shieldconst:
      - 2 # Shield DMG Absorption|{param2:F1P} Constant
    skilldot:
      - 3 # Frostfall Storm DMG|{param3:F1P}
  burst:
    burst:
      - 0 # Ice Storm DMG|{param0:F1P}
    burstskull:
      - 1 # Spiritvessel Skull DMG|{param1:F1P}