id: 90000005
key: "citlali"
rarity: QUALITY_ORANGE
body: BODY_GIRL
region: ASSOC_TYPE_NATLAN
element: Ice
weapon_class: WEAPON_CATALYST
icon_name: "UI_AvatarIcon_Ambor"
stats: {
   base_hp: 906
   base_atk: 10
   base_def: 59
   hp_curve: GROW_CURVE_HP_S5
   atk_curve: GROW_CURVE_ATTACK_S5
   def_cruve: GROW_CURVE_HP_S5
   promo_data: {
      max_level: 20
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
      }
      add_props: {
         prop_type: FIGHT_PROP_ELEMENT_MASTERY
      }
   }
   promo_data: {
      max_level: 40
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 777
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 141
      }
      add_props: {
         prop_type: FIGHT_PROP_ELEMENT_MASTERY
         value: 8
      }
      add_props: {
         prop_type: FIGHT_PROP_ELEMENT_MASTERY
      }
   }
   promo_data: {
      max_level: 50
add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1329.0585
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 241.1805
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 13.684
      }
      add_props: {
         prop_type: FIGHT_PROP_ELEMENT_MASTERY
         value: 28.8
      }
   }
   promo_data: {
      max_level: 60
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2065.1883
      }
add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 374.7639
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 21.2632
      }
      add_props: {
         prop_type: FIGHT_PROP_ELEMENT_MASTERY
         value: 57.6
      }
   }
   promo_data: {
      max_level: 70
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2617.2468
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 474.9444
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 26.9472
      }
      add_props: {
         prop_type: FIGHT_PROP_ELEMENT_MASTERY
         value: 57.6
      }
   }
   promo_data: {
      max_level: 80
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3169.3053
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 575.1249
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 32.6312
      }
      add_props: {
         prop_type: FIGHT_PROP_ELEMENT_MASTERY
         value: 86.4
      }
   }
   promo_data: {
      max_level: 90
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3721.4415
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 675.3195
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 38.316
      }
      add_props: {
         prop_type: FIGHT_PROP_ELEMENT_MASTERY
         value: 115.2
      }
   }
}
skill_details: {
   skill: 10262
   burst: 10265
   attack: 10261
   burst_energy_cost: 60
}
name_text_hash_map: 1021947691