package albedo

import (
	"fmt"

	"github.com/Karashina/gcsim-unofficial-clone/pkg/core/attacks"
	"github.com/Karashina/gcsim-unofficial-clone/pkg/core/attributes"
	"github.com/Karashina/gcsim-unofficial-clone/pkg/core/combat"
	"github.com/Karashina/gcsim-unofficial-clone/pkg/core/glog"
	"github.com/Karashina/gcsim-unofficial-clone/pkg/core/player/character"
	"github.com/Karashina/gcsim-unofficial-clone/pkg/enemy"
	"github.com/Karashina/gcsim-unofficial-clone/pkg/modifier"
)

const (
	hexereiBuffKey      = "albedo-hexerei-dmg"
	hexereiBuffDuration = 20 * 60 // 20s
)

// Transient Blossoms generated by Abiogenesis: Solar
// Isotoma deal 25% more DMG to opponents whose HP is below 50%.
func (c *char) a1() {
	if !c.Core.Combat.DamageMode {
		return
	}
	if c.Base.Ascension < 1 {
		return
	}
	m := make([]float64, attributes.EndStatType)
	m[attributes.DmgP] = 0.25
	c.AddAttackMod(character.AttackMod{
		Base: modifier.NewBase("albedo-a1", -1),
		Amount: func(atk *combat.AttackEvent, t combat.Target) ([]float64, bool) {
			if atk.Info.AttackTag != attacks.AttackTagElementalArt {
				return nil, false
			}
			// Can't be triggered by itself when refreshing
			if atk.Info.Abil == "Abiogenesis: Solar Isotoma" {
				return nil, false
			}
			if e, ok := t.(*enemy.Enemy); !(ok && e.HP()/e.MaxHP() < .5) {
				return nil, false
			}
			return m, true
		},
	})
}

// Using Rite of Progeniture: Tectonic Tide increases the Elemental Mastery of nearby party members by 125 for 10s.
func (c *char) a4() {
	if c.Base.Ascension < 4 {
		return
	}
	m := make([]float64, attributes.EndStatType)
	m[attributes.EM] = 125
	for _, char := range c.Core.Player.Chars() {
		char.AddStatMod(character.StatMod{
			Base:         modifier.NewBaseWithHitlag("albedo-a4", 600),
			AffectedStat: attributes.EM,
			Amount: func() ([]float64, bool) {
				return m, true
			},
		})
	}
}

// Hexerei: Secret Rite
// After creating a Solar Isotoma, nearby party members' DMG is increased by 4% per 1000 DEF (max 12%).
// After creating a Silver Isotoma, Hexerei party members' DMG is increased by 10% per 1000 DEF (max 30%).
func (c *char) hexereiSecretRite() {
	// Calculate DEF-based bonus
	def := c.TotalDef(false)
	defUnits := def / 1000.0

	// Apply different buffs based on Hexerei status
	for _, char := range c.Core.Player.Chars() {
		// Check if this character is Hexerei by querying their Condition
		isHexerei := false
		if result, err := char.Condition([]string{"hexerei"}); err == nil {
			if val, ok := result.(bool); ok && val {
				isHexerei = true
			}
		}

		var dmgBonus float64
		var maxBonus float64

		if c.isHexerei && isHexerei {
			// Silver Isotoma (Hexerei Albedo) -> Hexerei party members get stronger buff
			dmgBonus = 0.10 * defUnits // 10% per 1000 DEF
			maxBonus = 0.30            // max 30%
		} else {
			// Solar Isotoma -> all party members get normal buff
			dmgBonus = 0.04 * defUnits // 4% per 1000 DEF
			maxBonus = 0.12            // max 12%
		}

		// Cap at maximum
		if dmgBonus > maxBonus {
			dmgBonus = maxBonus
		}

		finalBonus := dmgBonus
		m := make([]float64, attributes.EndStatType)
		m[attributes.DmgP] = finalBonus

		char.AddAttackMod(character.AttackMod{
			Base: modifier.NewBaseWithHitlag(fmt.Sprintf("%s-%d", hexereiBuffKey, char.Index), hexereiBuffDuration),
			Amount: func(atk *combat.AttackEvent, t combat.Target) ([]float64, bool) {
				switch atk.Info.AttackTag {
				case attacks.AttackTagNormal,
					attacks.AttackTagExtra,
					attacks.AttackTagPlunge,
					attacks.AttackTagElementalArt,
					attacks.AttackTagElementalArtHold,
					attacks.AttackTagElementalBurst:
					return m, true
				}
				return nil, false
			},
		})
	}

	c.Core.Log.NewEvent("Albedo Hexerei: Secret Rite applied", glog.LogCharacterEvent, c.Index).
		Write("def", def).
		Write("is_hexerei", c.isHexerei)
}
