id: 10000630
key: "durin"
rarity: QUALITY_ORANGE
body: BODY_BOY
region: ASSOC_TYPE_MONDSTADT
element: Fire
weapon_class: WEAPON_SWORD_ONE_HAND
icon_name: "UI_AvatarIcon_Durin"
stats {
  base_hp: 967.6176
  base_atk: 26.9952
  base_def: 64.0224
  hp_curve: GROW_CURVE_HP_S5
  atk_curve: GROW_CURVE_ATTACK_S5
  def_cruve: GROW_CURVE_HP_S5
  promo_data {
  }
  promo_data {
    max_level: 40
    add_props {
      prop_type: FIGHT_PROP_BASE_HP
      value: 829.9144
    }
    add_props {
      prop_type: FIGHT_PROP_BASE_ATTACK
      value: 23.1552
    }
    add_props {
      prop_type: FIGHT_PROP_BASE_DEFENSE
      value: 54.9216
    }
  }
  promo_data {
    max_level: 50
    add_props {
      prop_type: FIGHT_PROP_BASE_HP
      value: 1419.3204
    }
    add_props {
      prop_type: FIGHT_PROP_BASE_ATTACK
      value: 39.5955
    }
    add_props {
      prop_type: FIGHT_PROP_BASE_DEFENSE
      value: 93.9412
    }
    add_props {
      prop_type: FIGHT_PROP_CRITICAL_HURT
      value: 0.096
    }
  }
  promo_data {
    max_level: 60
    add_props {
      prop_type: FIGHT_PROP_BASE_HP
      value: 2205.1404
    }
    add_props {
      prop_type: FIGHT_PROP_BASE_ATTACK
      value: 61.5090
    }
    add_props {
      prop_type: FIGHT_PROP_BASE_DEFENSE
      value: 145.9494
    }
    add_props {
      prop_type: FIGHT_PROP_CRITICAL_HURT
      value: 0.192
    }
  }
  promo_data {
    max_level: 70
    add_props {
      prop_type: FIGHT_PROP_BASE_HP
      value: 2794.5464
    }
    add_props {
      prop_type: FIGHT_PROP_BASE_ATTACK
      value: 77.9493
    }
    add_props {
      prop_type: FIGHT_PROP_BASE_DEFENSE
      value: 184.9688
    }
    add_props {
      prop_type: FIGHT_PROP_CRITICAL_HURT
      value: 0.192
    }
  }
  promo_data {
    max_level: 80
    add_props {
      prop_type: FIGHT_PROP_BASE_HP
      value: 3383.9524
    }
    add_props {
      prop_type: FIGHT_PROP_BASE_ATTACK
      value: 94.3896
    }
    add_props {
      prop_type: FIGHT_PROP_BASE_DEFENSE
      value: 223.9880
    }
    add_props {
      prop_type: FIGHT_PROP_CRITICAL_HURT
      value: 0.288
    }
  }
  promo_data {
    max_level: 90
    add_props {
      prop_type: FIGHT_PROP_BASE_HP
      value: 3973.3584
    }
    add_props {
      prop_type: FIGHT_PROP_BASE_ATTACK
      value: 110.8299
    }
    add_props {
      prop_type: FIGHT_PROP_BASE_DEFENSE
      value: 263.0072
    }
    add_props {
      prop_type: FIGHT_PROP_CRITICAL_HURT
      value: 0.384
    }
  }
}

skill_details: {
   skill: 10992
   burst: 10995
   attack: 10991
   burst_energy_cost: 70
}
name_text_hash_map: 1705786122
