// Code generated by "pipeline"; DO NOT EDIT.
package durin

import (
	_ "embed"

	"fmt"

	"slices"

	"github.com/Karashina/gcsim-unofficial-clone/pkg/core/action"
	"github.com/Karashina/gcsim-unofficial-clone/pkg/core/keys"
	"github.com/Karashina/gcsim-unofficial-clone/pkg/gcs/validation"
	"github.com/Karashina/gcsim-unofficial-clone/pkg/model"
	"google.golang.org/protobuf/encoding/prototext"
)

//go:embed data_gen.textproto
var pbData []byte
var base *model.AvatarData
var paramKeysValidation = map[action.Action][]string{
	5: {"collision"},
	6: {"collision"},
}

func init() {
	base = &model.AvatarData{}
	err := prototext.Unmarshal(pbData, base)
	if err != nil {
		panic(err)
	}
	validation.RegisterCharParamValidationFunc(keys.Durin, ValidateParamKeys)
}

func ValidateParamKeys(a action.Action, keys []string) error {
	valid, ok := paramKeysValidation[a]
	if !ok {
		return nil
	}
	for _, v := range keys {
		if !slices.Contains(valid, v) {
			if v == "movement" {
				return nil
			}
			return fmt.Errorf("key %v is invalid for action %v", v, a.String())
		}
	}
	return nil
}

func (x *char) Data() *model.AvatarData {
	return base
}

var (
	attack = [][]float64{
		attack_1,
		attack_2,
		attack_3,
		attack_4,
	}
)

var (
	// attack: attack_1 = [0]
	attack_1 = []float64{
		0.4570,
		0.4940,
		0.5310,
		0.5840,
		0.6210,
		0.6640,
		0.7220,
		0.7800,
		0.8390,
		0.9020,
		0.9660,
		0.9660,
		0.9660,
		0.9660,
		0.9660,
	}
	// attack: attack_2 = [1]
	attack_2 = []float64{
		0.4100,
		0.4430,
		0.4770,
		0.5240,
		0.5580,
		0.5960,
		0.6480,
		0.7010,
		0.7530,
		0.8110,
		0.8680,
		0.8680,
		0.8680,
		0.8680,
		0.8680,
	}
	// attack: attack_3 = [2] (per hit, 2 hits)
	attack_3 = []float64{
		0.2920,
		0.3150,
		0.3390,
		0.3730,
		0.3970,
		0.4240,
		0.4610,
		0.4980,
		0.5360,
		0.5760,
		0.6170,
		0.6170,
		0.6170,
		0.6170,
		0.6170,
	}
	// attack: attack_4 = [3]
	attack_4 = []float64{
		0.7120,
		0.7690,
		0.8270,
		0.9100,
		0.9680,
		1.0340,
		1.1250,
		1.2160,
		1.3070,
		1.4060,
		1.5060,
		1.5060,
		1.5060,
		1.5060,
		1.5060,
	}
	// attack: charge = [4]
	charge = []float64{
		1.1340,
		1.2270,
		1.3190,
		1.4510,
		1.5430,
		1.6490,
		1.7940,
		1.9390,
		2.0840,
		2.2420,
		2.4010,
		2.4010,
		2.4010,
		2.4010,
		2.4010,
	}
	// attack: collision = [5]
	collision = []float64{
		0.6390,
		0.6910,
		0.7430,
		0.8180,
		0.8700,
		0.9290,
		1.0110,
		1.0930,
		1.1750,
		1.2640,
		1.3530,
		1.3530,
		1.3530,
		1.3530,
		1.3530,
	}
	// attack: lowPlunge = [6]
	lowPlunge = []float64{
		1.2800,
		1.3800,
		1.4900,
		1.6400,
		1.7400,
		1.8600,
		2.0200,
		2.1900,
		2.3500,
		2.5300,
		2.7100,
		2.7100,
		2.7100,
		2.7100,
		2.7100,
	}
	// attack: highPlunge = [7]
	highPlunge = []float64{
		1.6000,
		1.7300,
		1.8600,
		2.0400,
		2.1700,
		2.3200,
		2.5300,
		2.7300,
		2.9300,
		3.1600,
		3.3800,
		3.3800,
		3.3800,
		3.3800,
		3.3800,
	}
	// skill: Confirmation of Purity DMG = [0]
	skillPurity = []float64{
		1.0560,
		1.1350,
		1.2140,
		1.3200,
		1.3990,
		1.4780,
		1.5840,
		1.6900,
		1.7950,
		1.9010,
		2.0060,
		2.1120,
		2.2440,
		2.2440,
		2.2440,
	}
	// skill: Denial of Darkness Hit 1 = [1]
	skillDenial1 = []float64{
		0.7220,
		0.7770,
		0.8310,
		0.9030,
		0.9570,
		1.0110,
		1.0840,
		1.1560,
		1.2280,
		1.3000,
		1.3730,
		1.4450,
		1.5350,
		1.5350,
		1.5350,
	}
	// skill: Denial of Darkness Hit 2 = [2]
	skillDenial2 = []float64{
		0.5320,
		0.5720,
		0.6120,
		0.6650,
		0.7050,
		0.7450,
		0.7980,
		0.8510,
		0.9040,
		0.9580,
		1.0110,
		1.0640,
		1.1310,
		1.1310,
		1.1310,
	}
	// skill: Denial of Darkness Hit 3 = [3]
	skillDenial3 = []float64{
		0.6460,
		0.6950,
		0.7430,
		0.8080,
		0.8560,
		0.9050,
		0.9700,
		1.0340,
		1.0990,
		1.1640,
		1.2280,
		1.2930,
		1.3740,
		1.3740,
		1.3740,
	}
	// skill: Energy Regeneration = [4]
	skillEnergyRegen = []float64{
		6.0,
		9.0,
		12.0,
		15.0,
		18.0,
		21.0,
		24.0,
		27.0,
		30.0,
		33.0,
		36.0,
		39.0,
		42.0,
		42.0,
		42.0,
	}
	// burst: Purity Hit 1 = [0]
	burstPurity1 = []float64{
		1.1900,
		1.2790,
		1.3680,
		1.4870,
		1.5760,
		1.6650,
		1.7840,
		1.9030,
		2.0220,
		2.1410,
		2.2600,
		2.3790,
		2.5280,
		2.5280,
		2.5280,
	}
	// burst: Purity Hit 2 = [1]
	burstPurity2 = []float64{
		0.9640,
		1.0360,
		1.1090,
		1.2050,
		1.2770,
		1.3500,
		1.4460,
		1.5420,
		1.6390,
		1.7350,
		1.8320,
		1.9280,
		2.0490,
		2.0490,
		2.0490,
	}
	// burst: Purity Hit 3 = [2]
	burstPurity3 = []float64{
		1.1180,
		1.2020,
		1.2860,
		1.3980,
		1.4820,
		1.5660,
		1.6780,
		1.7890,
		1.9010,
		2.0130,
		2.1250,
		2.2370,
		2.3770,
		2.3770,
		2.3770,
	}
	// burst: Darkness Hit 1 = [3]
	burstDarkness1 = []float64{
		1.2540,
		1.3480,
		1.4430,
		1.5680,
		1.6620,
		1.7560,
		1.8820,
		2.0070,
		2.1320,
		2.2580,
		2.3830,
		2.5090,
		2.6660,
		2.6660,
		2.6660,
	}
	// burst: Darkness Hit 2 = [4]
	burstDarkness2 = []float64{
		1.0180,
		1.0940,
		1.1700,
		1.2720,
		1.3480,
		1.4250,
		1.5260,
		1.6280,
		1.7300,
		1.8320,
		1.9330,
		2.0350,
		2.1620,
		2.1620,
		2.1620,
	}
	// burst: Darkness Hit 3 = [5] (same as Purity Hit 3)
	burstDarkness3 = []float64{
		1.1180,
		1.2020,
		1.2860,
		1.3980,
		1.4820,
		1.5660,
		1.6780,
		1.7890,
		1.9010,
		2.0130,
		2.1250,
		2.2370,
		2.3770,
		2.3770,
		2.3770,
	}
	// burst: Dragon of White Flame DMG = [6]
	dragonWhiteFlameDmg = []float64{
		0.9460,
		1.0170,
		1.0880,
		1.1830,
		1.2540,
		1.3250,
		1.4200,
		1.5140,
		1.6090,
		1.7040,
		1.7980,
		1.8930,
		2.0110,
		2.0110,
		2.0110,
	}
	// burst: Dragon of Dark Decay DMG = [7]
	dragonDarkDecayDmg = []float64{
		1.2980,
		1.3960,
		1.4930,
		1.6230,
		1.7200,
		1.8180,
		1.9480,
		2.0770,
		2.2070,
		2.3370,
		2.4670,
		2.5970,
		2.7590,
		2.7590,
		2.7590,
	}
)
