// Code generated by "pipeline"; DO NOT EDIT.
package aino

import (
	_ "embed"

	"fmt"
	"slices"

	"github.com/Karashina/gcsim-unofficial-clone/pkg/core/action"
	"github.com/Karashina/gcsim-unofficial-clone/pkg/core/keys"
	"github.com/Karashina/gcsim-unofficial-clone/pkg/gcs/validation"
	"github.com/Karashina/gcsim-unofficial-clone/pkg/model"
	"google.golang.org/protobuf/encoding/prototext"
)

//go:embed data_gen.textproto
var pbData []byte
var base *model.AvatarData
var paramKeysValidation = map[action.Action][]string{
	5: {"collision"},
	6: {"collision"},
}

func init() {
	base = &model.AvatarData{}
	err := prototext.Unmarshal(pbData, base)
	if err != nil {
		panic(err)
	}
	validation.RegisterCharParamValidationFunc(keys.Aino, ValidateParamKeys)
}

func ValidateParamKeys(a action.Action, keys []string) error {
	valid, ok := paramKeysValidation[a]
	if !ok {
		return nil
	}
	for _, v := range keys {
		if !slices.Contains(valid, v) {
			return fmt.Errorf("key %v is invalid for action %v", v, a.String())
		}
	}
	return nil
}

func (x *char) Data() *model.AvatarData {
	return base
}

var (
	attack = [][][]float64{
		{attack_1},
		{attack_2},
		attack_3,
	}
)

var (
	// attack: attack_1 = [0]
	attack_1 = []float64{
		0.665,
		0.719,
		0.773,
		0.851,
		0.905,
		0.967,
		1.052,
		1.137,
		1.222,
		1.315,
		1.407,
		1.407,
		1.407,
		1.407,
		1.407,
	}
	// attack: attack_2 = [1]
	attack_2 = []float64{
		0.662,
		0.716,
		0.770,
		0.847,
		0.901,
		0.962,
		1.047,
		1.131,
		1.216,
		1.308,
		1.401,
		1.401,
		1.401,
		1.401,
		1.401,
	}
	// attack: attack_3 = [2 3]
	attack_3 = [][]float64{
		{
			0.492,
			0.532,
			0.572,
			0.630,
			0.670,
			0.715,
			0.778,
			0.841,
			0.904,
			0.973,
			1.042,
			1.042,
			1.042,
			1.042,
			1.042,
		},
		{
			0.492,
			0.532,
			0.572,
			0.630,
			0.670,
			0.715,
			0.778,
			0.841,
			0.904,
			0.973,
			1.042,
			1.042,
			1.042,
			1.042,
			1.042,
		},
	}
	// attack: collision = [4]
	collision = []float64{
		0.746,
		0.807,
		0.867,
		0.954,
		1.015,
		1.084,
		1.180,
		1.275,
		1.370,
		1.474,
		1.578,
		1.682,
		1.787,
		1.891,
		1.995,
	}
	// attack: lowPlunge = [5]
	lowPlunge = []float64{
		1.49,
		1.61,
		1.73,
		1.91,
		2.03,
		2.17,
		2.36,
		2.55,
		2.74,
		2.95,
		3.16,
		3.36,
		3.57,
		3.78,
		3.99,
	}
	// attack: highPlunge = [6]
	highPlunge = []float64{
		1.86,
		2.01,
		2.17,
		2.38,
		2.53,
		2.71,
		2.95,
		3.18,
		3.42,
		3.68,
		3.94,
		4.20,
		4.46,
		4.72,
		4.98,
	}
	// skill: skillStage1 = [0]
	skillStage1 = []float64{
		0.656,
		0.705,
		0.754,
		0.820,
		0.869,
		0.918,
		0.984,
		1.050,
		1.115,
		1.181,
		1.246,
		1.312,
		1.394,
		1.476,
		1.476,
	}
	// skill: skillStage2 = [1]
	skillStage2 = []float64{
		1.888,
		2.030,
		2.171,
		2.360,
		2.502,
		2.643,
		2.832,
		3.021,
		3.210,
		3.398,
		3.587,
		3.776,
		4.012,
		4.248,
		4.248,
	}
	// burst: burst = [0]
	burst = []float64{
		0.201,
		0.216,
		0.231,
		0.251,
		0.266,
		0.282,
		0.302,
		0.322,
		0.342,
		0.362,
		0.382,
		0.402,
		0.427,
		0.427,
		0.427,
	}
)

