id: 90000603
key: "aino"
rarity: QUALITY_PURPLE
body: BODY_LOLI
region: 12
element: Water
weapon_class: WEAPON_CLAYMORE
icon_name: "UI_AvatarIcon_Ambor"
stats: {
   base_hp: 939
   base_atk: 20
   base_def: 51
   hp_curve: GROW_CURVE_HP_S4
   atk_curve: GROW_CURVE_ATTACK_S5
   def_cruve: GROW_CURVE_HP_S5
   promo_data: {
      max_level: 20
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
      }
      add_props: {
         prop_type: FIGHT_PROP_ELEMENT_MASTERY
      }
   }
   promo_data: {
      max_level: 40
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 701
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 38
      }
      add_props: {
         prop_type: FIGHT_PROP_ELEMENT_MASTERY
         value: 15
      }
      add_props: {
         prop_type: FIGHT_PROP_ELEMENT_MASTERY
      }
   }
   promo_data: {
      max_level: 50
add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1199.0605
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 64.999
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 25.6575
      }
      add_props: {
         prop_type: FIGHT_PROP_ELEMENT_MASTERY
         value: 24
      }
   }
   promo_data: {
      max_level: 60
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1863.1879
      }
add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 101.0002
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 39.8685
      }
      add_props: {
         prop_type: FIGHT_PROP_ELEMENT_MASTERY
         value: 48
      }
   }
   promo_data: {
      max_level: 70
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2361.2484
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 127.9992
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 50.526
      }
      add_props: {
         prop_type: FIGHT_PROP_ELEMENT_MASTERY
         value: 48
      }
   }
   promo_data: {
      max_level: 80
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2859.3089
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 154.9982
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 61.1835
      }
      add_props: {
         prop_type: FIGHT_PROP_ELEMENT_MASTERY
         value: 72
      }
   }
   promo_data: {
      max_level: 90
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3357.4395
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 182.001
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 71.8425
      }
      add_props: {
         prop_type: FIGHT_PROP_ELEMENT_MASTERY
         value: 96
      }
   }
}
skill_details: {
   skill: 10262
   burst: 10265
   attack: 10261
   burst_energy_cost: 50
}
name_text_hash_map: 1021947691
