package_name: ifa
genshin_id: 10000561
key: ifa
action_param_keys:
    attack:
        - param: "travel"
    charge:
        - param: "travel"
        - param: "hold"
    burst:
        - param: "travel"
skill_data_mapping:
    attack:
        attack_1:
            - 0 # 1-Hit DMG|{param0:F1P}
        attack_2:
            - 1 # 2-Hit DMG|{param1:F1P}
        attack_3:
            - 2 # 3-Hit DMG|{param2:F1P}×2
        charge:
            - 3 # Charged Attack DMG|{param4:F1P}
        collision:
            - 8 # Plunge DMG|{param6:F1P}
        lowPlunge:
            - 9 # Low/High Plunge DMG|{param7:P}/{param8:P}
        highPlunge:
            - 10 # Low/High Plunge DMG|{param7:P}/{param8:P}
    skill:
        tonicshot:
            - 0 # Tonicshot DMG|{param0:F1P}
        skillHealPct:
            - 1 # Tonicshot Healing On Hit (Percent)|{param1:F1P}
        skillHealCst:
            - 2 # Tonicshot Healing On Hit (Constant)|{param2:F1P}
    burst:
        burst:
            - 0 # Skill DMG|{param0:F1P}
        sedationmark:
            - 1 # Sedation Mark DMG|{param1:F1P}

