id: 90000003
key: "sigewinne"
rarity: QUALITY_ORANGE
body: BODY_LOLI
region: ASSOC_TYPE_FONTAINE
element: Water
weapon_class: WEAPON_BOW
icon_name: "UI_AvatarIcon_Ambor"
stats: {
   base_hp: 1039
   base_atk: 15
   base_def: 39
   hp_curve: GROW_CURVE_HP_S5
   atk_curve: GROW_CURVE_ATTACK_S5
   def_cruve: GROW_CURVE_HP_S5
   promo_data: {
      max_level: 20
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
      }
      add_props: {
         prop_type: FIGHT_PROP_HP_PERCENT
      }
   }
   promo_data: {
      max_level: 40
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 891
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 33
      }
      add_props: {
         prop_type: FIGHT_PROP_HP_PERCENT
         value: 13
      }
      add_props: {
         prop_type: FIGHT_PROP_HP_PERCENT
      }
   }
   promo_data: {
      max_level: 50
add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1524.0555
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 56.4465
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 22.2365
      }
      add_props: {
         prop_type: FIGHT_PROP_HP_PERCENT
         value: 0.072
      }
   }
   promo_data: {
      max_level: 60
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2368.1889
      }
add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 87.7107
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 34.5527
      }
      add_props: {
         prop_type: FIGHT_PROP_HP_PERCENT
         value: 0.144
      }
   }
   promo_data: {
      max_level: 70
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3001.2444
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 111.1572
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 43.7892
      }
      add_props: {
         prop_type: FIGHT_PROP_HP_PERCENT
         value: 0.144
      }
   }
   promo_data: {
      max_level: 80
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3634.2999
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 134.6037
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 53.0257
      }
      add_props: {
         prop_type: FIGHT_PROP_HP_PERCENT
         value: 0.216
      }
   }
   promo_data: {
      max_level: 90
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 4267.4445
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 158.0535
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 62.2635
      }
      add_props: {
         prop_type: FIGHT_PROP_HP_PERCENT
         value: 0.288
      }
   }
}
skill_details: {
   skill: 10262
   burst: 10265
   attack: 10261
   burst_energy_cost: 70
}
name_text_hash_map: 1021947691