// Code generated by "pipeline"; DO NOT EDIT.
package varka

import (
	_ "embed"

	"fmt"
	"slices"

	"github.com/Karashina/gcsim-unofficial-clone/pkg/core/action"
	"github.com/Karashina/gcsim-unofficial-clone/pkg/core/keys"
	"github.com/Karashina/gcsim-unofficial-clone/pkg/gcs/validation"
	"github.com/Karashina/gcsim-unofficial-clone/pkg/model"
	"google.golang.org/protobuf/encoding/prototext"
)

//go:embed data_gen.textproto
var pbData []byte
var base *model.AvatarData
var paramKeysValidation = map[action.Action][]string{
	5: {"collision"},
	6: {"collision"},
}

func init() {
	base = &model.AvatarData{}
	err := prototext.Unmarshal(pbData, base)
	if err != nil {
		panic(err)
	}
	validation.RegisterCharParamValidationFunc(keys.Varka, ValidateParamKeys)
}

func ValidateParamKeys(a action.Action, keys []string) error {
	valid, ok := paramKeysValidation[a]
	if !ok {
		return nil
	}
	for _, v := range keys {
		if !slices.Contains(valid, v) {
			if v == "movement" {
				return nil
			}
			return fmt.Errorf("key %v is invalid for action %v", v, a.String())
		}
	}
	return nil
}

func (x *char) Data() *model.AvatarData {
	return base
}

// ==================== Normal Attack scaling (11 entries → padded to 15) ====================
var (
	attack = [][]float64{
		attack_1,
	}
	attackMulti = [][][]float64{
		nil, // N1 uses single-hit
		{attack_2a, attack_2b},
		{attack_3a, attack_3b},
		{attack_4a, attack_4b},
		{attack_5a, attack_5b},
	}
)

var (
	// Normal Attack 1-Hit DMG
	attack_1 = []float64{
		0.655, 0.708, 0.761, 0.837, 0.891, 0.951, 1.035, 1.119, 1.203, 1.294, 1.385, 1.385, 1.385, 1.385, 1.385,
	}
	// Normal Attack 2-Hit 1st sub-hit
	attack_2a = []float64{
		0.240, 0.259, 0.279, 0.307, 0.326, 0.349, 0.379, 0.410, 0.441, 0.474, 0.508, 0.508, 0.508, 0.508, 0.508,
	}
	// Normal Attack 2-Hit 2nd sub-hit
	attack_2b = []float64{
		0.446, 0.482, 0.518, 0.570, 0.606, 0.648, 0.705, 0.761, 0.818, 0.881, 0.943, 0.943, 0.943, 0.943, 0.943,
	}
	// Normal Attack 3-Hit 1st sub-hit
	attack_3a = []float64{
		0.324, 0.351, 0.377, 0.415, 0.441, 0.471, 0.513, 0.554, 0.596, 0.641, 0.686, 0.686, 0.686, 0.686, 0.686,
	}
	// Normal Attack 3-Hit 2nd sub-hit
	attack_3b = []float64{
		0.602, 0.651, 0.700, 0.770, 0.820, 0.876, 0.953, 1.030, 1.107, 1.191, 1.275, 1.275, 1.275, 1.275, 1.275,
	}
	// Normal Attack 4-Hit 1st sub-hit
	attack_4a = []float64{
		0.554, 0.599, 0.645, 0.709, 0.754, 0.806, 0.877, 0.947, 1.018, 1.096, 1.173, 1.173, 1.173, 1.173, 1.173,
	}
	// Normal Attack 4-Hit 2nd sub-hit
	attack_4b = []float64{
		0.298, 0.323, 0.347, 0.382, 0.406, 0.434, 0.472, 0.510, 0.548, 0.590, 0.632, 0.632, 0.632, 0.632, 0.632,
	}
	// Normal Attack 5-Hit 1st sub-hit
	attack_5a = []float64{
		0.697, 0.754, 0.811, 0.892, 0.949, 1.014, 1.103, 1.192, 1.281, 1.379, 1.476, 1.476, 1.476, 1.476, 1.476,
	}
	// Normal Attack 5-Hit 2nd sub-hit
	attack_5b = []float64{
		0.376, 0.406, 0.437, 0.480, 0.511, 0.546, 0.594, 0.642, 0.690, 0.742, 0.795, 0.795, 0.795, 0.795, 0.795,
	}

	// Charged Attack 1st sub-hit
	charge_a = []float64{
		0.856, 0.926, 0.996, 1.095, 1.165, 1.245, 1.354, 1.464, 1.573, 1.693, 1.812, 1.812, 1.812, 1.812, 1.812,
	}
	// Charged Attack 2nd sub-hit
	charge_b = []float64{
		0.461, 0.499, 0.536, 0.590, 0.627, 0.670, 0.729, 0.788, 0.847, 0.912, 0.976, 0.976, 0.976, 0.976, 0.976,
	}

	// Plunge collision
	collision = []float64{
		0.746, 0.807, 0.867, 0.954, 1.015, 1.084, 1.180, 1.275, 1.370, 1.474, 1.578, 1.578, 1.578, 1.578, 1.578,
	}
	// Low plunge DMG
	lowPlunge = []float64{
		1.49, 1.61, 1.73, 1.91, 2.03, 2.17, 2.36, 2.55, 2.74, 2.95, 3.16, 3.16, 3.16, 3.16, 3.16,
	}
	// High plunge DMG
	highPlunge = []float64{
		1.86, 2.01, 2.17, 2.38, 2.53, 2.71, 2.95, 3.18, 3.42, 3.68, 3.94, 3.94, 3.94, 3.94, 3.94,
	}
)

// ==================== Skill scaling (13 entries → padded to 15) ====================
var (
	// Windbound Execution initial Skill DMG (Anemo)
	skillDmg = []float64{
		2.784, 2.993, 3.202, 3.480, 3.689, 3.898, 4.176, 4.454, 4.733, 5.011, 5.290, 5.568, 5.916, 5.916, 5.916,
	}

	// Sturm und Drang 1-Hit DMG
	sturmN1 = []float64{
		0.818, 0.885, 0.951, 1.047, 1.113, 1.189, 1.294, 1.399, 1.503, 1.617, 1.732, 1.846, 1.960, 1.960, 1.960,
	}
	// Sturm und Drang 2-Hit 1st (Anemo)
	sturmN2a = []float64{
		0.300, 0.324, 0.349, 0.384, 0.408, 0.436, 0.474, 0.513, 0.551, 0.593, 0.635, 0.676, 0.718, 0.718, 0.718,
	}
	// Sturm und Drang 2-Hit 2nd (Other)
	sturmN2b = []float64{
		0.557, 0.602, 0.648, 0.712, 0.758, 0.809, 0.881, 0.952, 1.023, 1.101, 1.179, 1.256, 1.334, 1.334, 1.334,
	}
	// Sturm und Drang 3-Hit 1st (Anemo)
	sturmN3a = []float64{
		0.405, 0.438, 0.471, 0.519, 0.552, 0.589, 0.641, 0.693, 0.745, 0.801, 0.858, 0.915, 0.971, 0.971, 0.971,
	}
	// Sturm und Drang 3-Hit 2nd (Other)
	sturmN3b = []float64{
		0.753, 0.814, 0.876, 0.963, 1.024, 1.094, 1.191, 1.287, 1.383, 1.488, 1.594, 1.699, 1.804, 1.804, 1.804,
	}
	// Sturm und Drang 4-Hit 1st (Other)
	sturmN4a = []float64{
		0.693, 0.749, 0.806, 0.886, 0.943, 1.007, 1.096, 1.184, 1.273, 1.370, 1.466, 1.563, 1.660, 1.660, 1.660,
	}
	// Sturm und Drang 4-Hit 2nd (Anemo)
	sturmN4b = []float64{
		0.373, 0.403, 0.434, 0.477, 0.508, 0.542, 0.590, 0.638, 0.685, 0.738, 0.790, 0.842, 0.894, 0.894, 0.894,
	}
	// Sturm und Drang 5-Hit 1st (Other)
	sturmN5a = []float64{
		0.872, 0.943, 1.014, 1.115, 1.186, 1.267, 1.379, 1.490, 1.602, 1.723, 1.845, 1.967, 2.088, 2.088, 2.088,
	}
	// Sturm und Drang 5-Hit 2nd (Anemo)
	sturmN5b = []float64{
		0.469, 0.508, 0.546, 0.600, 0.639, 0.682, 0.742, 0.802, 0.863, 0.928, 0.994, 1.059, 1.125, 1.125, 1.125,
	}

	// Sturm und Drang Charged Attack 1st (Other)
	sturmCA_a = []float64{
		1.070, 1.158, 1.245, 1.369, 1.456, 1.556, 1.693, 1.830, 1.967, 2.116, 2.265, 2.415, 2.564, 2.564, 2.564,
	}
	// Sturm und Drang Charged Attack 2nd (Anemo)
	sturmCA_b = []float64{
		0.576, 0.623, 0.670, 0.737, 0.784, 0.838, 0.912, 0.985, 1.059, 1.139, 1.220, 1.300, 1.381, 1.381, 1.381,
	}

	// Four Winds' Ascension 1st hit (Other)
	fwaOther = []float64{
		1.758, 1.889, 2.021, 2.197, 2.329, 2.461, 2.636, 2.812, 2.988, 3.164, 3.339, 3.515, 3.735, 3.735, 3.735,
	}
	// Four Winds' Ascension 2nd hit (Anemo)
	fwaAnemo = []float64{
		0.946, 1.017, 1.088, 1.183, 1.254, 1.325, 1.420, 1.514, 1.609, 1.704, 1.798, 1.893, 2.011, 2.011, 2.011,
	}

	// Azure Devour: Other element hits (1st & 3rd)
	azureOther = []float64{
		0.936, 1.006, 1.076, 1.170, 1.240, 1.310, 1.404, 1.498, 1.591, 1.685, 1.778, 1.872, 1.989, 1.989, 1.989,
	}
	// Azure Devour: Anemo hits (2nd & 4th)
	azureAnemo = []float64{
		0.504, 0.542, 0.580, 0.630, 0.668, 0.706, 0.756, 0.806, 0.857, 0.907, 0.958, 1.008, 1.071, 1.071, 1.071,
	}
)

// ==================== Burst scaling (13 entries → padded to 15) ====================
var (
	// Northwind Avatar 1st Hit DMG
	burst1 = []float64{
		3.370, 3.622, 3.875, 4.212, 4.465, 4.717, 5.054, 5.391, 5.728, 6.065, 6.402, 6.739, 7.160, 7.160, 7.160,
	}
	// Northwind Avatar 2nd Hit DMG
	burst2 = []float64{
		1.814, 1.950, 2.087, 2.268, 2.404, 2.540, 2.722, 2.903, 3.084, 3.266, 3.447, 3.629, 3.856, 3.856, 3.856,
	}
)
