package_name: skirk
genshin_id: 10000570
key: skirk
skill_data_mapping:
  attack:
    attack_1:
      - 0 # 1-Hit DMG|{param0:F1P}
    attack_2:
      - 1 # 2-Hit DMG|{param1:F1P}
    attack_3:
      - 2 # 3-Hit DMG|{param2:F1P}+{param3:F1P}
      - 3 # 3-Hit DMG|{param2:F1P}+{param3:F1P}
    attack_4:
      - 4 # 4-Hit DMG|{param4:F1P}+{param5:F1P}+{param6:F1P}
    attack_5:
      - 5 # 5-Hit DMG|{param9:F1P}
    charge:
      - 6 # Charged Attack DMG|{param10:F1P}
    collision:
      - 13 # Plunge DMG|{param12:F1P}
    lowPlunge:
      - 11 # Low/High Plunge DMG|{param13:P}/{param14:P}
    highPlunge:
      - 12 # Low/High Plunge DMG|{param13:P}/{param14:P}
  skill:
    spattack_1:
      - 0 # 1-Hit DMG|{param0:F1P}
    spattack_2:
      - 1 # 2-Hit DMG|{param1:F1P}
    spattack_3:
      - 2 # 3-Hit DMG|{param2:F1P}+{param3:F1P}
      - 3 # 3-Hit DMG|{param2:F1P}+{param3:F1P}
    spattack_4:
      - 4 # 4-Hit DMG|{param4:F1P}+{param5:F1P}+{param6:F1P}
      - 5 # 4-Hit DMG|{param4:F1P}+{param5:F1P}+{param6:F1P}
    spattack_5:
      - 6 # 5-Hit DMG|{param9:F1P}
    sp charge:
      - 7 # Charged Attack DMG|{param10:F1P}
    collision:
      - 8 # Plunge DMG|{param12:F1P}
    lowPlunge:
      - 10 # Low/High Plunge DMG|{param13:P}/{param14:P}
    highPlunge:
      - 9 # Low/High Plunge DMG|{param13:P}/{param14:P}
  burst:
    burst:
      - 0
    burstlast:
      - 1
    burstDMGUp:
      - 2
