// Code generated by "pipeline"; DO NOT EDIT.
package chasca

import (
	_ "embed"

	"fmt"
	"github.com/genshinsim/gcsim/pkg/core/action"
	"github.com/genshinsim/gcsim/pkg/core/keys"
	"github.com/genshinsim/gcsim/pkg/gcs/validation"
	"github.com/genshinsim/gcsim/pkg/model"
	"google.golang.org/protobuf/encoding/prototext"
	"slices"
)

//go:embed data_gen.textproto
var pbData []byte
var base *model.AvatarData
var paramKeysValidation = map[action.Action][]string{
	3: {"travel"},
	7: {"travel"},
}

func init() {
	base = &model.AvatarData{}
	err := prototext.Unmarshal(pbData, base)
	if err != nil {
		panic(err)
	}
	validation.RegisterCharParamValidationFunc(keys.Chasca, ValidateParamKeys)
}

func ValidateParamKeys(a action.Action, keys []string) error {
	valid, ok := paramKeysValidation[a]
	if !ok {
		return nil
	}
	for _, v := range keys {
		if !slices.Contains(valid, v) {
			return fmt.Errorf("key %v is invalid for action %v", v, a.String())
		}
	}
	return nil
}

func (x *char) Data() *model.AvatarData {
	return base
}

var (
	attack = [][][]float64{
		{attack_1},
		{attack_2},
		attack_3,
		attack_4,
	}
)

var (
	// attack: attack_1 = [0]
	attack_1 = []float64{
		0.48, 
		0.51888, 
		0.55824, 
		0.61392, 
		0.6528, 
		0.69744, 
		0.75888, 
		0.82032, 
		0.88176, 
		0.94896, 
		1.01568, 
		1.08288, 
		1.1496, 
		1.1496, 
		1.1496, 		
	}
	// attack: attack_2 = [1]
	attack_2 = []float64{
		0.446, 
		0.482126, 
		0.518698, 
		0.570434, 
		0.60656, 
		0.648038, 
		0.705126, 
		0.762214, 
		0.819302, 
		0.881742, 
		0.943736, 
		1.006176, 
		1.06817, 
		1.06817, 
		1.06817, 		
	}
	// attack: attack_3 = [2 2]
	attack_3 = [][]float64{
		{
			0.297, 
			0.321057, 
			0.345411, 
			0.379863, 
			0.40392, 
			0.431541, 
			0.469557, 
			0.507573, 
			0.545589, 
			0.587169, 
			0.628452, 
			0.670032, 
			0.711315, 
			0.711315, 
			0.711315, 			
		},
		{
			0.297, 
			0.321057, 
			0.345411, 
			0.379863, 
			0.40392, 
			0.431541, 
			0.469557, 
			0.507573, 
			0.545589, 
			0.587169, 
			0.628452, 
			0.670032, 
			0.711315, 
			0.711315, 
			0.711315, 			
		},
	}
	// attack: attack_4 = [3 ]
	attack_4 = [][]float64{
		{
			0.255, 
			0.275655, 
			0.296565, 
			0.326145, 
			0.3468, 
			0.370515, 
			0.403155, 
			0.435795, 
			0.468435, 
			0.504135, 
			0.53958, 
			0.57528, 
			0.610725, 
			0.610725, 
			0.610725, 	
		},
		{
			0.255, 
			0.275655, 
			0.296565, 
			0.326145, 
			0.3468, 
			0.370515, 
			0.403155, 
			0.435795, 
			0.468435, 
			0.504135, 
			0.53958, 
			0.57528, 
			0.610725, 
			0.610725, 
			0.610725, 	
		},
	}
	// attack: fullaim = [4]
	fullaim = []float64{
		1.24, 
		1.34044, 
		1.44212, 
		1.58596, 
		1.6864, 
		1.80172, 
		1.96044, 
		2.11916, 
		2.27788, 
		2.45148, 
		2.62384, 
		2.79744, 
		2.9698, 
		2.9698, 
		2.9698, 		
	}
	// attack: highPlunge = [5]
	highPlunge = []float64{
		1.42, 
		1.53502, 
		1.65146, 
		1.81618, 
		1.9312, 
		2.06326, 
		2.24502, 
		2.42678, 
		2.60854, 
		2.80734, 
		3.00472, 
		3.20352, 
		3.4009, 
		3.4009, 
		3.4009, 			
	}
	// skill: resonance = [0]
	resonance = []float64{
		0.6, 
		0.645, 
		0.69, 
		0.75, 
		0.795, 
		0.84, 
		0.9, 
		0.96, 
		1.02, 
		1.08, 
		1.14, 
		1.2, 
		1.275, 
		1.275, 
		1.275, 		
	}
	// skill: tap = [1]
	tap = []float64{
		0.36, 
		0.387, 
		0.414, 
		0.45, 
		0.477, 
		0.504, 
		0.54, 
		0.576, 
		0.612, 
		0.648, 
		0.684, 
		0.72, 
		0.765, 
		0.765, 
		0.765, 		
	}
	// skill: shadowhunt = [2]
	shadowhunt = []float64{
		0.488, 
		0.5246, 
		0.5612, 
		0.61, 
		0.6466, 
		0.6832, 
		0.732, 
		0.7808, 
		0.8296, 
		0.8784, 
		0.9272, 
		0.976, 
		1.037, 
		1.037, 
		1.037, 		
	}
	// skill: shiningshadowhunt = [3]
	shiningshadowhunt = []float64{
		1.666, 
		1.79095, 
		1.9159, 
		2.0825, 
		2.20745, 
		2.3324, 
		2.499, 
		2.6656, 
		2.8322, 
		2.9988, 
		3.1654, 
		3.332, 
		3.54025, 
		3.54025, 
		3.54025, 		
	}
	// burst: burst = [0]
	burst = []float64{
		0.88, 
		0.946, 
		1.012, 
		1.1, 
		1.166, 
		1.232, 
		1.32, 
		1.408, 
		1.496, 
		1.584, 
		1.672, 
		1.76, 
		1.87, 
		1.87, 
		1.87, 		
	}
	// burst: soulseeker = [1]
	soulseeker = []float64{
		1.034, 
		1.11155, 
		1.1891, 
		1.2925, 
		1.37005, 
		1.4476, 
		1.551, 
		1.6544, 
		1.7578, 
		1.8612, 
		1.9646, 
		2.068, 
		2.19725, 
		2.19725, 
		2.19725, 		
	}
	// burst: radiantsoulseeker = [2]
	radiantsoulseeker = []float64{
		2.068, 
		2.2231, 
		2.3782, 
		2.585, 
		2.7401, 
		2.8952, 
		3.102, 
		3.3088, 
		3.5156, 
		3.7224, 
		3.9292, 
		4.136, 
		4.3945, 
		4.3945, 
		4.3945, 		
	}
)
