package_name: chasca
genshin_id: 90000002
key: chasca
action_param_keys:
  attack:
    - param: "travel"
  aim:
    - param: "travel"
skill_data_mapping:
  attack:
    attack_1:
      - 0 # 1-Hit DMG|{param0:F1P}
    attack_2:
      - 1 # 2-Hit DMG|{param1:F1P}
    attack_3:
      - 2 # 3-Hit DMG|{param2:F1P}
    attack_4:
      - 3 # 4-Hit DMG|{param3:F1P}
    fullaim:
      - 4 # Fully Charged Aim DMG|{param4:F1P}
    highplunge:
      - 5 # High Plunge DMG|{param5:F1P}
  skill:
    resonance:
      - 0 # Resonance DMG |{param0:F1P} 
    tap:
      - 1 # Multitarget Fire Tap DMG |{param1:F1P}
    shadowhunt:
      - 2 # Shadowhunt Shell DMG |{param2:F1P}
    shiningshadowhunt:
      - 3 # Shining Shadowhunt Shell DMG |{param3:F1P}
  burst:
    burst:
      - 0 # Galesplitting Soulseeker Shell DMG |{param0:F1P}
    soulseeker:
      - 1 # Soulseeker Shell DMG |{param1:F1P}
    radiantsoulseeker:
      - 2 # Radiant Soulseeker Shell DMG |{param2:F1P}