id: 90000000
key: "chasca"
rarity: QUALITY_ORANGE
body: BODY_LADY
region: ASSOC_TYPE_NATLAN
element: Wind
weapon_class: WEAPON_BOW
icon_name: "UI_AvatarIcon_Ambor"
stats: {
   base_hp: 763
   base_atk: 27
   base_def: 48
   hp_curve: GROW_CURVE_HP_S5
   atk_curve: GROW_CURVE_ATTACK_S5
   def_cruve: GROW_CURVE_HP_S5
   promo_data: {
      max_level: 20
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
      }
   }
   promo_data: {
      max_level: 40
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 654
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 41
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 23
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
      }
   }
   promo_data: {
      max_level: 50
add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1118.667
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 70.1305
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 39.3415
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.048
      }
   }
   promo_data: {
      max_level: 60
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1738.2666
      }
add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 108.9739
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 61.1317
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.096
      }
   }
   promo_data: {
      max_level: 70
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2202.9336
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 138.1044
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 77.4732
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.096
      }
   }
   promo_data: {
      max_level: 80
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2667.6006
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 167.2349
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 93.8147
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.144
      }
   }
   promo_data: {
      max_level: 90
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3132.333
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 196.3695
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 110.1585
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.192
      }
   }
}
skill_details: {
   skill: 10262
   burst: 10265
   attack: 10261
   burst_energy_cost: 60
}
name_text_hash_map: 1021947691