id: 90660
key: "linnea"
rarity: QUALITY_ORANGE
body: BODY_GIRL
region: 12
element: Rock
weapon_class: WEAPON_BOW
icon_name: "UI_AvatarIcon_Linnea"
stats: {
   base_hp: 770.0
   base_atk: 11.0
   base_def: 71.0
   hp_curve: GROW_CURVE_HP_S5
   atk_curve: GROW_CURVE_ATTACK_S5
   def_cruve: GROW_CURVE_HP_S5
   promo_data: {
      max_level: 20
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
      }
   }
   promo_data: {
      max_level: 40
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 661.0
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 61.0
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 10.0
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
      }
   }
   promo_data: {
      max_level: 50
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1130.0
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 104.0
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 16.0
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.048
      }
   }
   promo_data: {
      max_level: 60
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1755.0
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 161.0
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 25.0
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.096
      }
   }
   promo_data: {
      max_level: 70
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2224.0
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 204.0
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 32.0
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.096
      }
   }
   promo_data: {
      max_level: 80
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2694.0
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 247.0
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 39.0
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.144
      }
   }
   promo_data: {
      max_level: 90
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3163.0
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 290.0
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 45.0
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.192
      }
   }
}
skill_details: {
   skill: 90660002
   burst: 90660003
   attack: 90660001
   burst_energy_cost: 60
}
