package_name: escoffier
genshin_id: 10000560
key: escoffier
action_param_keys:
  low_plunge:
    - param: "collision"
  high_plunge:
    - param: "collision"
icd_groups:
  - group_name: ICDGroupEscoffierCookingMek
    reset_timer: 90
    ele_app_sequence: [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    damage_sequence: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
skill_data_mapping:
  attack: # Normal Attack: Shadow-Hunting Spear
    attack_1:
      - 0 # 1-Hit DMG|{param0:F1P}
    attack_2:
      - 1 # 2-Hit DMG|{param1:F1P}
    attack_3:
      - 2 # 3-Hit DMG 1|{param2:F1P}
      - 3 # 3-Hit DMG 2|{param3:F1P}
    charge:
      - 4 # Charged Attack DMG|{param4:F1P}
    collision:
      - 6 # Plunge DMG|{param6:F1P}
    lowPlunge:
      - 7 # Low/High Plunge DMG|{param7:P}/{param8:P}
    highPlunge:
      - 8 # Low/High Plunge DMG|{param7:P}/{param8:P}
  skill:
    skill:
      - 0 # Skill DMG|{param0:F1P}
    skillCookingMek:
      - 1 # Frosty Parfait DMG|{param1:F1P}
    skillArkhe:
      - 2 # Surging Blade DMG|{param2:F1P}
  burst:
    burst:
      - 0 # Skill DMG|{param0:F1P}
    burstHealPct:
      - 1 # Healing(Percentage)|{param1:F1P}
    burstHealCst:
      - 2 # Healing(Constant)|{param2:F1P}