id: 90000560
key: "escoffier"
rarity: QUALITY_ORANGE
body: BODY_GIRL
region: ASSOC_TYPE_FONTAINE
element: Ice
weapon_class: WEAPON_POLE
icon_name: "UI_AvatarIcon_Ambor"
stats: {
   base_hp: 1039
   base_atk: 27
   base_def: 57
   hp_curve: GROW_CURVE_HP_S5
   atk_curve: GROW_CURVE_ATTACK_S5
   def_cruve: GROW_CURVE_HP_S5
   promo_data: {
      max_level: 20
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
      }
   }
   promo_data: {
      max_level: 40
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 891
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 49
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 23
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
      }
   }
   promo_data: {
      max_level: 50
add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1524.0555
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 83.8145
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 39.3415
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.048
      }
   }
   promo_data: {
      max_level: 60
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2368.1889
      }
add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 130.2371
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 61.1317
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.096
      }
   }
   promo_data: {
      max_level: 70
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3001.2444
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 165.0516
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 77.4732
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.096
      }
   }
   promo_data: {
      max_level: 80
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3634.2999
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 199.8661
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 93.8147
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.144
      }
   }
   promo_data: {
      max_level: 90
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 4267.4445
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 234.6855
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 110.1585
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.192
      }
   }
}
skill_details: {
   skill: 10262
   burst: 10265
   attack: 10261
   burst_energy_cost: 60
}
name_text_hash_map: 1021947691