id: 90000600
key: "lauma"
rarity: QUALITY_ORANGE
body: BODY_LADY
region: 12
element: Grass
weapon_class: WEAPON_CATALYST
icon_name: "UI_AvatarIcon_Ambor"
stats: {
   base_hp: 829
   base_atk: 20
   base_def: 52
   hp_curve: GROW_CURVE_HP_S5
   atk_curve: GROW_CURVE_ATTACK_S5
   def_cruve: GROW_CURVE_HP_S5
   promo_data: {
      max_level: 20
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
      }
      add_props: {
         prop_type: FIGHT_PROP_ELEMENT_MASTERY
         value: 200.0
      }
   }
   promo_data: {
      max_level: 40
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 712
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 45
      }
      add_props: {
         prop_type: FIGHT_PROP_ELEMENT_MASTERY
         value: 18
      }
      add_props: {
         prop_type: FIGHT_PROP_ELEMENT_MASTERY
         value: 200.0
      }
   }
   promo_data: {
      max_level: 50
add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1217.876
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 76.9725
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 30.789
      }
      add_props: {
         prop_type: FIGHT_PROP_ELEMENT_MASTERY
         value: 228.8
      }
   }
   promo_data: {
      max_level: 60
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1892.4248
      }
add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 119.6055
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 47.8422
      }
      add_props: {
         prop_type: FIGHT_PROP_ELEMENT_MASTERY
         value: 257.6
      }
   }
   promo_data: {
      max_level: 70
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2398.3008
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 151.578
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 60.6312
      }
      add_props: {
         prop_type: FIGHT_PROP_ELEMENT_MASTERY
         value: 257.6
      }
   }
   promo_data: {
      max_level: 80
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2904.1768
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 183.5505
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 73.4202
      }
      add_props: {
         prop_type: FIGHT_PROP_ELEMENT_MASTERY
         value: 286.4
      }
   }
   promo_data: {
      max_level: 90
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3410.124
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 215.5275
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 86.211
      }
      add_props: {
         prop_type: FIGHT_PROP_ELEMENT_MASTERY
         value: 315.2
      }
   }
}
skill_details: {
   skill: 10262
   burst: 10265
   attack: 10261
   burst_energy_cost: 60
}
name_text_hash_map: 1021947691