// Code generated by "pipeline"; DO NOT EDIT.
package lauma

import (
	_ "embed"

	"fmt"
	"slices"

	"github.com/Karashina/gcsim-unofficial-clone/pkg/core/action"
	"github.com/Karashina/gcsim-unofficial-clone/pkg/core/keys"
	"github.com/Karashina/gcsim-unofficial-clone/pkg/gcs/validation"
	"github.com/Karashina/gcsim-unofficial-clone/pkg/model"
	"google.golang.org/protobuf/encoding/prototext"
)

//go:embed data_gen.textproto
var pbData []byte
var base *model.AvatarData
var paramKeysValidation = map[action.Action][]string{
	1: {"hold"},
}

func init() {
	base = &model.AvatarData{}
	err := prototext.Unmarshal(pbData, base)
	if err != nil {
		panic(err)
	}
	validation.RegisterCharParamValidationFunc(keys.Lauma, ValidateParamKeys)
}

func ValidateParamKeys(a action.Action, keys []string) error {
	valid, ok := paramKeysValidation[a]
	if !ok {
		return nil
	}
	for _, v := range keys {
		if !slices.Contains(valid, v) {
			return fmt.Errorf("key %v is invalid for action %v", v, a.String())
		}
	}
	return nil
}

func (x *char) Data() *model.AvatarData {
	return base
}

var (
	attack = [][]float64{
		attack_1,
		attack_2,
		attack_3,
	}
)

var (
	// attack: attack_1 = [0]
	attack_1 = []float64{
		0.337,
		0.362275,
		0.38755,
		0.42125,
		0.446525,
		0.4718,
		0.5055,
		0.5392,
		0.5729,
		0.6066,
		0.6403,
		0.674,
		0.716125,
		0.716125,
		0.716125,
	}
	// attack: attack_2 = [1]
	attack_2 = []float64{
		0.318,
		0.34185,
		0.3657,
		0.3975,
		0.42135,
		0.4452,
		0.477,
		0.5088,
		0.5406,
		0.5724,
		0.6042,
		0.636,
		0.67575,
		0.67575,
		0.67575,
	}
	// attack: attack_3 = [2]
	attack_3 = []float64{
		0.445,
		0.478375,
		0.51175,
		0.55625,
		0.589625,
		0.623,
		0.6675,
		0.712,
		0.7565,
		0.801,
		0.8455,
		0.89,
		0.945625,
		0.945625,
		0.945625,
	}
	// skill: skillPress = [0]
	skillPress = []float64{
		1.216,
		1.3072,
		1.3984,
		1.52,
		1.6112,
		1.7024,
		1.824,
		1.9456,
		2.0672,
		2.1888,
		2.3104,
		2.432,
		2.584,
		2.584,
		2.584,
	}
	// skill: skillHold1 = [1]
	skillHold1 = []float64{
		1.581,
		1.699575,
		1.81815,
		1.97625,
		2.094825,
		2.2134,
		2.3715,
		2.5296,
		2.6877,
		2.8458,
		3.0039,
		3.162,
		3.359625,
		3.359625,
		3.359625,
	}
	// skill: skillHold2 = [2]
	skillHold2 = []float64{
		1.52,
		1.634,
		1.748,
		1.9,
		2.014,
		2.128,
		2.28,
		2.432,
		2.584,
		2.736,
		2.888,
		3.04,
		3.23,
		3.23,
		3.23,
	}
	// skill: skillDotATK = [3]
	skillDotATK = []float64{
		0.96,
		1.032,
		1.104,
		1.2,
		1.272,
		1.344,
		1.44,
		1.536,
		1.632,
		1.728,
		1.824,
		1.92,
		2.04,
		2.04,
		2.04,
	}
	// skill: skillDotEM = [4]
	skillDotEM = []float64{
		1.92,
		2.064,
		2.208,
		2.4,
		2.544,
		2.688,
		2.88,
		3.072,
		3.264,
		3.456,
		3.648,
		3.84,
		4.08,
		4.08,
		4.08,
	}
	// skill: skillRESShred = [5]
	skillRESShred = []float64{
		0.025,
		0.05,
		0.075,
		0.1,
		0.125,
		0.15,
		0.175,
		0.2,
		0.225,
		0.25,
		0.28,
		0.31,
		0.34,
		0.34,
		0.34,
	}
	// burst: burstBuffBloom = [0]
	burstBuffBloom = []float64{
		2.778,
		2.98635,
		3.1947,
		3.4725,
		3.68085,
		3.8892,
		4.167,
		4.4448,
		4.7226,
		5.0004,
		5.2782,
		5.556,
		5.90325,
		5.90325,
		5.90325,
	}
	// burst: burstBuffLBloom = [1]
	burstBuffLBloom = []float64{
		2.222,
		2.38865,
		2.5553,
		2.7775,
		2.94415,
		3.1108,
		3.333,
		3.5552,
		3.7774,
		3.9996,
		4.2218,
		4.444,
		4.72175,
		4.72175,
		4.72175,
	}
)

