// Code generated by "pipeline"; DO NOT EDIT.
package lauma

import (
	_ "embed"

	"github.com/genshinsim/gcsim/pkg/core/action"
	"github.com/genshinsim/gcsim/pkg/core/keys"
	"github.com/genshinsim/gcsim/pkg/gcs/validation"
	"github.com/genshinsim/gcsim/pkg/model"
	"google.golang.org/protobuf/encoding/prototext"
)

//go:embed data_gen.textproto
var pbData []byte
var base *model.AvatarData

func init() {
	base = &model.AvatarData{}
	err := prototext.Unmarshal(pbData, base)
	if err != nil {
		panic(err)
	}
	validation.RegisterCharParamValidationFunc(keys.Lauma, ValidateParamKeys)
}

func ValidateParamKeys(a action.Action, keys []string) error {
	// No special validation for now
	return nil
}

func (x *char) Data() *model.AvatarData {
	return base
}