// Code generated by "pipeline"; DO NOT EDIT.
package lauma

import (
	_ "embed"

	"fmt"
	"slices"

	"github.com/genshinsim/gcsim/pkg/core/action"
	"github.com/genshinsim/gcsim/pkg/core/keys"
	"github.com/genshinsim/gcsim/pkg/gcs/validation"
	"github.com/genshinsim/gcsim/pkg/model"
	"google.golang.org/protobuf/encoding/prototext"
)

//go:embed data_gen.textproto
var pbData []byte
var base *model.AvatarData
var paramKeysValidation = map[action.Action][]string{
	1: {"hold"},
}

func init() {
	base = &model.AvatarData{}
	err := prototext.Unmarshal(pbData, base)
	if err != nil {
		panic(err)
	}
	validation.RegisterCharParamValidationFunc(keys.Lauma, ValidateParamKeys)
}

func ValidateParamKeys(a action.Action, keys []string) error {
	valid, ok := paramKeysValidation[a]
	if !ok {
		return nil
	}
	for _, v := range keys {
		if !slices.Contains(valid, v) {
			return fmt.Errorf("key %v is invalid for action %v", v, a.String())
		}
	}
	return nil
}

func (x *char) Data() *model.AvatarData {
	return base
}

var (
	attack = [][]float64{
		attack_1,
		attack_2,
		attack_3,
	}
)

var (
	// attack: attack_1 = [0]
	attack_1 = []float64{
		0.52,
		0.559,
		0.598,
		0.65,
		0.689,
		0.728,
		0.78,
		0.832,
		0.884,
		0.936,
		0.988,
		1.04,
		1.105,
		1.17,
		1.235,
	}
	// attack: attack_2 = [1]
	attack_2 = []float64{
		0.48,
		0.516,
		0.552,
		0.6,
		0.636,
		0.672,
		0.72,
		0.768,
		0.816,
		0.864,
		0.912,
		0.96,
		1.02,
		1.08,
		1.14,
	}
	// attack: attack_3 = [2]
	attack_3 = []float64{
		0.74,
		0.7955,
		0.851,
		0.925,
		0.9805,
		1.036,
		1.11,
		1.184,
		1.258,
		1.332,
		1.406,
		1.48,
		1.5725,
		1.665,
		1.7575,
	}
	// skill: skillPress = [0]
	skillPress = []float64{
		1.44,
		1.548,
		1.656,
		1.8,
		1.908,
		2.016,
		2.16,
		2.304,
		2.448,
		2.592,
		2.736,
		2.88,
		3.06,
		3.24,
		3.42,
	}
	// skill: skillHold1 = [1]
	skillHold1 = []float64{
		1.92,
		2.064,
		2.208,
		2.4,
		2.544,
		2.688,
		2.88,
		3.072,
		3.264,
		3.456,
		3.648,
		3.84,
		4.08,
		4.32,
		4.56,
	}
	// skill: skillHold2 = [2]
	skillHold2 = []float64{
		2.4,
		2.58,
		2.76,
		3.0,
		3.18,
		3.36,
		3.6,
		3.84,
		4.08,
		4.32,
		4.56,
		4.8,
		5.1,
		5.4,
		5.7,
	}
	// skill: skillDotATK = [3]
	skillDotATK = []float64{
		0.36,
		0.387,
		0.414,
		0.45,
		0.477,
		0.504,
		0.54,
		0.576,
		0.612,
		0.648,
		0.684,
		0.72,
		0.765,
		0.81,
		0.855,
	}
	// skill: skillDotEM = [4]
	skillDotEM = []float64{
		1.44,
		1.548,
		1.656,
		1.8,
		1.908,
		2.016,
		2.16,
		2.304,
		2.448,
		2.592,
		2.736,
		2.88,
		3.06,
		3.24,
		3.42,
	}
	// burst: burstBuffBloom = [0]
	burstBuffBloom = []float64{
		1.0,
		1.075,
		1.15,
		1.25,
		1.325,
		1.4,
		1.5,
		1.6,
		1.7,
		1.8,
		1.9,
		2.0,
		2.125,
		2.25,
		2.375,
	}
	// burst: burstBuffLBloom = [1]
	burstBuffLBloom = []float64{
		1.2,
		1.29,
		1.38,
		1.5,
		1.59,
		1.68,
		1.8,
		1.92,
		2.04,
		2.16,
		2.28,
		2.4,
		2.55,
		2.7,
		2.85,
	}
)
