package_name: ororon
genshin_id: 90000001
key: ororon
action_param_keys:
    attack:
      - param: "travel"
    aim:
      - param: "hold"
      - param: "travel"
      - param: "weakspot"
skill_data_mapping:
  attack:
    aim:
      - 3 # Aimed Shot|{param3:F1P}
    auto_1:
      - 0 # 1-Hit DMG|{param0:F1P}
    auto_2:
      - 1 # 2-Hit DMG|{param1:F1P}
    auto_3:
      - 2 # 3-Hit DMG|{param2:F1P}
    fullaim:
      - 4 # Fully-Charged Aimed Shot|{param4:P}
  skill:
    skill:
      - 0 # Spirit Orb DMG|{param0:F1P}
  burst:
    burst:
      - 0 # Ritual DMG|{param0:P}
    burstdot:
      - 1 # Soundwave Collision DMG|{param0:P}