// Code generated by "pipeline"; DO NOT EDIT.
package ororon

import (
	_ "embed"

	"fmt"
	"github.com/genshinsim/gcsim/pkg/core/action"
	"github.com/genshinsim/gcsim/pkg/core/keys"
	"github.com/genshinsim/gcsim/pkg/gcs/validation"
	"github.com/genshinsim/gcsim/pkg/model"
	"google.golang.org/protobuf/encoding/prototext"
	"slices"
)

//go:embed data_gen.textproto
var pbData []byte
var base *model.AvatarData
var paramKeysValidation = map[action.Action][]string{
	3: {"travel"},
	7: {"hold", "travel", "weakspot"},
}

func init() {
	base = &model.AvatarData{}
	err := prototext.Unmarshal(pbData, base)
	if err != nil {
		panic(err)
	}
	validation.RegisterCharParamValidationFunc(keys.Ororon, ValidateParamKeys)
}

func ValidateParamKeys(a action.Action, keys []string) error {
	valid, ok := paramKeysValidation[a]
	if !ok {
		return nil
	}
	for _, v := range keys {
		if !slices.Contains(valid, v) {
			return fmt.Errorf("key %v is invalid for action %v", v, a.String())
		}
	}
	return nil
}

func (x *char) Data() *model.AvatarData {
	return base
}

var (
	auto = [][]float64{
		auto_1,
		auto_2,
		auto_3,
	}
)

var (
	// attack: aim = [3]
	aim = []float64{
		0.4386,
		0.4743,
		0.51,
		0.561,
		0.5967,
		0.6375,
		0.6936,
		0.7497,
		0.8058,
		0.867,
		0.9282,
		0.9894,
		1.0506,
		1.1118,
		1.173,
	}
	// attack: auto_1 = [0]
	auto_1 = []float64{
		0.506, 
		0.546986, 
		0.588478, 
		0.647174, 
		0.68816, 
		0.735218, 
		0.799986, 
		0.864754, 
		0.929522, 
		1.000362, 
		1.070696, 
		1.141536, 
		1.21187, 
		1.21187, 
		1.21187, 
					
	}
	// attack: auto_2 = [1]
	auto_2 = []float64{
		0.444, 
		0.479964, 
		0.516372, 
		0.567876, 
		0.60384, 
		0.645132, 
		0.701964, 
		0.758796, 
		0.815628, 
		0.877788, 
		0.939504, 
		1.001664, 
		1.06338, 
		1.06338, 
		1.06338, 	
		
	}
	// attack: auto_3 = [2]
	auto_3 = []float64{
		0.698, 
		0.754538, 
		0.811774, 
		0.892742, 
		0.94928, 
		1.014194, 
		1.103538, 
		1.192882, 
		1.282226, 
		1.379946, 
		1.476968, 
		1.574688, 
		1.67171, 
		1.67171, 
		1.67171, 		
	}
	// attack: fullaim = [4]
	fullaim = []float64{
		1.24,
		1.333,
		1.426,
		1.55,
		1.643,
		1.736,
		1.86,
		1.984,
		2.108,
		2.232,
		2.356,
		2.48,
		2.635,
		2.79,
		2.945,
	}
	// skill: skill = [0]
	skill = []float64{
		1.976, 
		2.1242, 
		2.2724, 
		2.47, 
		2.6182, 
		2.7664, 
		2.964, 
		3.1616, 
		3.3592, 
		3.5568, 
		3.7544, 
		3.952, 
		4.199, 
		4.199, 
		4.199, 		
	}
	// burst: burst = [0]
	burst = []float64{
		1.744, 
		1.8748, 
		2.0056, 
		2.18, 
		2.3108, 
		2.4416, 
		2.616, 
		2.7904, 
		2.9648, 
		3.1392, 
		3.3136, 
		3.488, 
		3.706, 
		3.706, 
		3.706, 		
	}
	// burst: burstdot = [1]
	burstdot = []float64{
		0.332, 
		0.3569, 
		0.3818, 
		0.415, 
		0.4399, 
		0.4648, 
		0.498, 
		0.5312, 
		0.5644, 
		0.5976, 
		0.6308, 
		0.664, 
		0.7055, 
		0.7055, 
		0.7055, 		
	}
)
