package_name: sethos
genshin_id: 90000002
key: sethos
action_param_keys:
  attack:
    - param: "travel"
  aim:
    - param: "hold"
    - param: "travel"
    - param: "weakspot"
skill_data_mapping:
  attack:
    aim:
      - 4 # Aimed Shot|{param4:F1P}
    attack_1:
      - 0 # 1-Hit DMG|{param0:F1P}
    attack_2:
      - 1 # 2-Hit DMG|{param1:F1P}
      - 2 # 2-Hit DMG|{param1:F1P}
    attack_3:
      - 3 # 3-Hit DMG|{param2:F1P}×2
    shadowpiercing:
      - 7 # Shadowpiercing Shot DMG (ATK)|{param7:F1P}
    shadowpiercingem:
      - 8 # Shadowpiercing Shot DMG (EM)|{param7:F1P}
    fullaim:
      - 6 # Level 1 Aimed Shot|{param5:P}
  skill:
    skill:
      - 0 # Skill DMG|{param0:F1P}
  burst:
    burst:
      - 0 # Dusk Bolt DMG Increase|{param0:F1P}