id: 90000002
key: "sethos"
rarity: QUALITY_PURPLE
body: BODY_BOY
region: ASSOC_TYPE_SUMERU
element: Electric
weapon_class: WEAPON_BOW
icon_name: "UI_AvatarIcon_Ambor"
stats: {
   base_hp: 821
   base_atk: 19
   base_def: 47
   hp_curve: GROW_CURVE_HP_S4
   atk_curve: GROW_CURVE_ATTACK_S5
   def_cruve: GROW_CURVE_HP_S5
   promo_data: {
      max_level: 20
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
      }
      add_props: {
         prop_type: FIGHT_PROP_ELEMENT_MASTERY
      }
   }
   promo_data: {
      max_level: 40
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 821
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 47
      }
      add_props: {
         prop_type: FIGHT_PROP_ELEMENT_MASTERY
         value: 19
      }
      add_props: {
         prop_type: FIGHT_PROP_ELEMENT_MASTERY
      }
   }
   promo_data: {
      max_level: 50
add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1404.34210526316
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 80.3947368421053
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 32.5
      }
      add_props: {
         prop_type: FIGHT_PROP_ELEMENT_MASTERY
         value: 24
      }
   }
   promo_data: {
      max_level: 60
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2182.13157894737
      }
add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 124.921052631579
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 50.5
      }
      add_props: {
         prop_type: FIGHT_PROP_ELEMENT_MASTERY
         value: 48
      }
   }
   promo_data: {
      max_level: 70
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2765.47339723278
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 158.315773044995
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 63.9999933586149
      }
      add_props: {
         prop_type: FIGHT_PROP_ELEMENT_MASTERY
         value: 48
      }
   }
   promo_data: {
      max_level: 80
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3348.81564598481
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 191.710518101445
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 77.4999966793074
      }
      add_props: {
         prop_type: FIGHT_PROP_ELEMENT_MASTERY
         value: 72
      }
   }
   promo_data: {
      max_level: 90
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3932.15789473684
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 225.105263157895
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 91
      }
      add_props: {
         prop_type: FIGHT_PROP_ELEMENT_MASTERY
         value: 96
      }
   }
}
skill_details: {
   skill: 10262
   burst: 10265
   attack: 10261
   burst_energy_cost: 60
}
name_text_hash_map: 1021947691