id: 90000002
key: "sethos"
rarity: QUALITY_PURPLE
body: BODY_BOY
region: ASSOC_TYPE_SUMERU
element: Electric
weapon_class: WEAPON_BOW
icon_name: "UI_AvatarIcon_Ambor"
stats: {
   base_hp: 821
   base_atk: 19
   base_def: 47
   hp_curve: GROW_CURVE_HP_S4
   atk_curve: GROW_CURVE_ATTACK_S5
   def_cruve: GROW_CURVE_HP_S5
   promo_data: {
      max_level: 20
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
      }
      add_props: {
         prop_type: FIGHT_PROP_ELEMENT_MASTERY
      }
   }
   promo_data: {
      max_level: 40
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 613
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 35
      }
      add_props: {
         prop_type: FIGHT_PROP_ELEMENT_MASTERY
         value: 14
      }
      add_props: {
         prop_type: FIGHT_PROP_ELEMENT_MASTERY
      }
   }
   promo_data: {
      max_level: 50
add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1048.5365
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 59.8675
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 23.947
      }
      add_props: {
         prop_type: FIGHT_PROP_ELEMENT_MASTERY
         value: 24
      }
   }
   promo_data: {
      max_level: 60
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1629.2927
      }
add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 93.0265
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 37.2106
      }
      add_props: {
         prop_type: FIGHT_PROP_ELEMENT_MASTERY
         value: 48
      }
   }
   promo_data: {
      max_level: 70
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2064.8292
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 117.894
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 47.1576
      }
      add_props: {
         prop_type: FIGHT_PROP_ELEMENT_MASTERY
         value: 48
      }
   }
   promo_data: {
      max_level: 80
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2500.3657
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 142.7615
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 57.1046
      }
      add_props: {
         prop_type: FIGHT_PROP_ELEMENT_MASTERY
         value: 72
      }
   }
   promo_data: {
      max_level: 90
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2935.9635
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 167.6325
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 67.053
      }
      add_props: {
         prop_type: FIGHT_PROP_ELEMENT_MASTERY
         value: 96
      }
   }
}
skill_details: {
   skill: 10262
   burst: 10265
   attack: 10261
   burst_energy_cost: 60
}
name_text_hash_map: 1021947691