package_name: ineffa
genshin_id: 10000580
key: ineffa
action_param_keys:
  low_plunge:
    - param: "collision"
  high_plunge:
    - param: "collision"
  skill_data_mapping:
      attack:
        attack_1:
          - 0 # 1-Hit DMG|{param0:F1P}
        attack_2:
          - 1 # 2-Hit DMG|{param1:F1P}
        attack_3:
          - 2 # 3-Hit DMG|{param2:F1P}+{param3:F1P}
          - 3 # 3-Hit DMG|{param2:F1P}+{param3:F1P}
        attack_4:
          - 4 # 4-Hit DMG|{param1:F1P}
        charge:
          - 5 # Charged Attack DMG|{param4:F1P}
        collision:
          - 6 # Plunge DMG|{param6:F1P}
        lowPlunge:
          - 7 # Low Plunge DMG|{param7:P}
        highPlunge:
          - 8 # High Plunge DMG|{param8:P}
      skill:
        skill:
          - 0 # Skill DMG|{param0:F1P}
        skillDot:
          - 1 # Shield DMG Absorption|{param1:F1P} atk
        shieldPct:
          - 2 # Shield DMG Absorption|{param2:F1} constant
        shieldCst:
          - 3 # Birgitta Discharge DMG|{param3:F1P}
      burst:
        burst:
          - 0 # Burst DMG|{param0:F1P}
