package_name: iansan
genshin_id: 10000102
key: iansan
skill_data_mapping:
  attack:
    attack_1:
      - 0 # 1-Hit DMG|{param0:F1P}
    attack_2:
      - 1 # 2-Hit DMG|{param1:F1P}
    attack_3:
      - 2 # 3-Hit DMG|{param2:F1P}
    charge:
      - 3 # Charged Attack DMG|{param3:F1P}
  skill:
    skill:
      - 0 # |{param0:F1P}
  burst:
    burst:
      - 0 # Skill DMG|{param0:F2P} Max HP
