package_name: mavuika
genshin_id: 10000004
key: mavuika
action_param_keys:
  charge:
    - param: "hold"
  skill:
    - param: "hold"
  low_plunge:
      - param: "collision"
  high_plunge:
      - param: "collision"
skill_data_mapping:
  attack:
    attack_1:
      - 0 # 1-Hit DMG|{param0:F1P}
    attack_2:
      - 1 # 2-Hit DMG|{param1:F1P}
      - 1 # 2-Hit DMG|{param1:F1P}
    attack_3:
      - 2 # 3-Hit DMG|{param2:F1P}
      - 2 # 3-Hit DMG|{param2:F1P}
      - 2 # 3-Hit DMG|{param2:F1P}
    attack_4:
      - 3 # 1-Hit DMG|{param3:F1P}
    charge:
      - 4 # Charged Attack DMG|{param4:F1P}
    collision:
      - 5 # Plunge DMG|{param5:F1P}
    lowPlunge:
      - 6 # Low/High Plunge DMG|{param6:P}/{param7:P}
    highPlunge:
      - 7 # Low/High Plunge DMG|{param6:P}/{param7:P}
  skill:
    bikeattack_1:
      - 0 # Flamestrider Normal Attack 1-Hit DMG|{param0:F1P}
    bikeattack_2:
      - 1 # Flamestrider Normal Attack 2-Hit DMG|{param1:F1P}
    bikeattack_3:
      - 2 # Flamestrider Normal Attack 3-Hit DMG|{param2:F1P}
    bikeattack_4:
      - 3 # Flamestrider Normal Attack 4-Hit DMG|{param3:F1P}
    bikeattack_5:
      - 4 # Flamestrider Normal Attack 5-Hit DMG|{param4:F1P}
    bikedash:
      - 5 # Flamestrider Sprint DMG|{param5:F1P}
    bikecharge:
      - 6 # Flamestrider Charged Attack Cyclic DMG|{param6:F1P}
    bikechargefinal:
      - 7 # Flamestrider Charged Attack Final DMG|{param7:F1P}
    bikeplunge:
      - 8 # Flamestrider Plunge DMG|{param8:F1P}
    skill:
      - 9 # Skill DMG|{param9:F1P}
    skilldot:
      - 10 # Ring of Searing Radiance DMG|{param10:F1P}
  burst:
    burst:
      - 0 # Skill DMG|{param0:F1P}
    burstbonus:
      - 1 # Sunfell Slice DMG Bonus|{param1:F1P}
    burstnabonus:
      - 2 # Flamestrider Normal Attack DMG Bonus|{param2:F1P}
    burstcabonus:
      - 3 # Flamestrider Charged Attack DMG Bonus|{param3:F1P}
