id: 90000004
key: "mavuika"
rarity: QUALITY_ORANGE
body: BODY_LADY
region: ASSOC_TYPE_NATLAN
element: Fire
weapon_class: WEAPON_CLAYMORE
icon_name: "UI_AvatarIcon_Ambor"
stats: {
   base_hp: 977
   base_atk: 28
   base_def: 62
   hp_curve: GROW_CURVE_HP_S5
   atk_curve: GROW_CURVE_ATTACK_S5
   def_cruve: GROW_CURVE_HP_S5
   promo_data: {
      max_level: 20
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
      }
   }
   promo_data: {
      max_level: 40
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 838
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 53
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
         value: 24
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
      }
   }
   promo_data: {
      max_level: 50
add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1433.399
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 90.6565
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 41.052
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
         value: 0.096
      }
   }
   promo_data: {
      max_level: 60
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2227.3202
      }
add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 140.8687
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 63.7896
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
         value: 0.192
      }
   }
   promo_data: {
      max_level: 70
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2822.7192
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 178.5252
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 80.8416
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
         value: 0.192
      }
   }
   promo_data: {
      max_level: 80
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3418.1182
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 216.1817
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 97.8936
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
         value: 0.288
      }
   }
   promo_data: {
      max_level: 90
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 4013.601
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 253.8435
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 114.948
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
         value: 0.384
      }
   }
}
skill_details: {
   skill: 10262
   burst: 10265
   attack: 10261
   burst_energy_cost: 0
}
name_text_hash_map: 1021947691