package main

import (
	"encoding/csv"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
)

func readCSV(path string, skipHeader bool) ([][]string, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()
	r := csv.NewReader(f)
	r.FieldsPerRecord = -1
	out := [][]string{}
	first := true
	for {
		rec, err := r.Read()
		if err == io.EOF {
			break
		}
		if err != nil {
			return nil, err
		}
		if first && skipHeader {
			first = false
			continue
		}
		first = false
		out = append(out, rec)
	}
	return out, nil
}

func writeJS(path string, charMap, weaponMap, artifactMap map[string]string) error {
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()

	// Write JS that merges into existing maps so it can be loaded after app.js
	fmt.Fprintln(f, "// Generated by cmd/generate-webui-mappings/main.go")
	fmt.Fprintln(f, "(function(){")
	// CHAR
	fmt.Fprintln(f, "window.CHAR_TO_JP = Object.assign(window.CHAR_TO_JP || {}, {")
	for k, v := range charMap {
		fmt.Fprintf(f, "    %q: %q,\n", k, v)
	}
	fmt.Fprintln(f, "});")

	// WEAPON
	fmt.Fprintln(f, "window.WEAPON_TO_JP = Object.assign(window.WEAPON_TO_JP || {}, {")
	for k, v := range weaponMap {
		fmt.Fprintf(f, "    %q: %q,\n", k, v)
	}
	fmt.Fprintln(f, "});")

	// ARTIFACT
	fmt.Fprintln(f, "window.ARTIFACT_TO_JP = Object.assign(window.ARTIFACT_TO_JP || {}, {")
	for k, v := range artifactMap {
		fmt.Fprintf(f, "    %q: %q,\n", k, v)
	}
	fmt.Fprintln(f, "});")

	fmt.Fprintln(f, "})();")
	return nil
}

func main() {
	// Base paths
	root := filepath.Join("cmd", "gcsim")
	charCSV := filepath.Join(root, "chatracterData", "charactertoJP.csv")
	artifactCSV := filepath.Join(root, "artifactData", "artifact.csv")
	weaponDir := filepath.Join(root, "weaponData")

	charMap := map[string]string{}
	weaponMap := map[string]string{}
	artifactMap := map[string]string{}

	// Read characters
	if recs, err := readCSV(charCSV, true); err == nil {
		for _, r := range recs {
			if len(r) < 2 {
				continue
			}
			jp := strings.TrimSpace(r[0])
			key := strings.TrimSpace(r[1])
			if key == "" || jp == "" {
				continue
			}
			charMap[key] = jp
		}
	}

	// Read artifacts
	if recs, err := readCSV(artifactCSV, true); err == nil {
		for _, r := range recs {
			if len(r) < 2 {
				continue
			}
			jp := strings.TrimSpace(r[0])
			key := strings.TrimSpace(r[1])
			if key == "" || jp == "" {
				continue
			}
			artifactMap[key] = jp
		}
	}

	// Read each weapon CSV in weaponData
	files, err := os.ReadDir(weaponDir)
	if err == nil {
		for _, fi := range files {
			if fi.IsDir() || !strings.HasSuffix(fi.Name(), ".csv") {
				continue
			}
			path := filepath.Join(weaponDir, fi.Name())
			if recs, err := readCSV(path, true); err == nil {
				for _, r := range recs {
					if len(r) < 2 {
						continue
					}
					jp := strings.TrimSpace(r[0])
					key := strings.TrimSpace(r[1])
					if key == "" || jp == "" {
						continue
					}
					weaponMap[key] = jp
				}
			}
		}
	}

	outPath := filepath.Join("webui", "jp_mappings.generated.js")
	if err := writeJS(outPath, charMap, weaponMap, artifactMap); err != nil {
		fmt.Fprintf(os.Stderr, "failed to write generated file: %v\n", err)
		os.Exit(2)
	}
	fmt.Println("wrote", outPath)
}
