// Code generated by "pipeline"; DO NOT EDIT.
package illuga

import (
	_ "embed"

	"github.com/Karashina/gcsim-unofficial-clone/pkg/model"
	"google.golang.org/protobuf/encoding/prototext"
)

//go:embed data_gen.textproto
var pbData []byte
var base *model.AvatarData

func init() {
	base = &model.AvatarData{}
	err := prototext.Unmarshal(pbData, base)
	if err != nil {
		panic(err)
	}
}

func (x *char) Data() *model.AvatarData {
	return base
}

var (
	attack = [][][]float64{
		{attack_1},
		{attack_2},
		{attack_3_1, attack_3_2},
		{attack_4},
	}
)

// Normal Attack 1-Hit DMG (15 entries)
var attack_1 = []float64{
	0.474, 0.512, 0.551, 0.606, 0.644, 0.688, 0.749, 0.810, 0.870, 0.936,
	1.002, 1.002, 1.002, 1.002, 1.002,
}

// Normal Attack 2-Hit DMG (15 entries)
var attack_2 = []float64{
	0.485, 0.525, 0.564, 0.621, 0.660, 0.705, 0.767, 0.829, 0.892, 0.959,
	1.027, 1.027, 1.027, 1.027, 1.027,
}

// Normal Attack 3-Hit DMG part 1 (15 entries)
var attack_3_1 = []float64{
	0.314, 0.340, 0.366, 0.402, 0.428, 0.457, 0.497, 0.537, 0.577, 0.621,
	0.665, 0.665, 0.665, 0.665, 0.665,
}

// Normal Attack 3-Hit DMG part 2 (15 entries)
var attack_3_2 = []float64{
	0.314, 0.340, 0.366, 0.402, 0.428, 0.457, 0.497, 0.537, 0.577, 0.621,
	0.665, 0.665, 0.665, 0.665, 0.665,
}

// Normal Attack 4-Hit DMG (15 entries)
var attack_4 = []float64{
	0.763, 0.825, 0.887, 0.976, 1.038, 1.109, 1.206, 1.304, 1.401, 1.508,
	1.614, 1.614, 1.614, 1.614, 1.614,
}

// Charged Attack DMG (15 entries)
var charge = []float64{
	1.110, 1.201, 1.291, 1.420, 1.510, 1.614, 1.756, 1.898, 2.040, 2.195,
	2.350, 2.350, 2.350, 2.350, 2.350,
}

// Plunge DMG (15 entries)
var plunge = []float64{
	0.639, 0.691, 0.743, 0.818, 0.870, 0.929, 1.011, 1.093, 1.175, 1.264,
	1.353, 1.353, 1.353, 1.353, 1.353,
}

// Low Plunge DMG (15 entries)
var lowPlunge = []float64{
	1.28, 1.38, 1.49, 1.64, 1.74, 1.86, 2.02, 2.19, 2.35, 2.53,
	2.71, 2.71, 2.71, 2.71, 2.71,
}

// High Plunge DMG (15 entries)
var highPlunge = []float64{
	1.60, 1.73, 1.86, 2.04, 2.17, 2.32, 2.53, 2.73, 2.93, 3.16,
	3.38, 3.38, 3.38, 3.38, 3.38,
}

// ========== Elemental Skill ==========
// Tap DMG - EM scaling (15 entries)
var skillTapEM = []float64{
	4.83, 5.19, 5.55, 6.03, 6.39, 6.76, 7.24, 7.72, 8.20, 8.69,
	9.17, 9.65, 10.25, 10.25, 10.25,
}

// Tap DMG - DEF scaling (15 entries)
var skillTapDEF = []float64{
	2.41, 2.59, 2.77, 3.02, 3.20, 3.38, 3.62, 3.86, 4.10, 4.34,
	4.58, 4.83, 5.13, 5.13, 5.13,
}

// Hold DMG - EM scaling (15 entries)
var skillHoldEM = []float64{
	6.03, 6.48, 6.94, 7.54, 7.99, 8.44, 9.05, 9.65, 10.25, 10.86,
	11.46, 12.06, 12.82, 12.82, 12.82,
}

// Hold DMG - DEF scaling (15 entries)
var skillHoldDEF = []float64{
	3.02, 3.24, 3.47, 3.77, 4.00, 4.22, 4.52, 4.83, 5.13, 5.43,
	5.73, 6.03, 6.41, 6.41, 6.41,
}

// ========== Elemental Burst ==========
// Skill DMG - EM scaling (15 entries)
var burstEM = []float64{
	8.27, 8.89, 9.51, 10.34, 10.96, 11.58, 12.41, 13.24, 14.06, 14.89,
	15.72, 16.54, 17.58, 17.58, 17.58,
}

// Skill DMG - DEF scaling (15 entries)
var burstDEF = []float64{
	4.14, 4.45, 4.76, 5.17, 5.48, 5.79, 6.20, 6.62, 7.03, 7.44,
	7.86, 8.27, 8.79, 8.79, 8.79,
}

// Geo DMG Bonus - EM scaling (15 entries)
var burstGeoBonusEM = []float64{
	0.336, 0.361, 0.386, 0.420, 0.445, 0.470, 0.504, 0.538, 0.571, 0.605,
	0.638, 0.672, 0.714, 0.714, 0.714,
}

// Lunar-Crystallize Reaction DMG Bonus - EM scaling (15 entries)
var burstLCrsBonusEM = []float64{
	2.259, 2.429, 2.598, 2.824, 2.993, 3.163, 3.389, 3.615, 3.841, 4.067,
	4.292, 4.518, 4.801, 4.801, 4.801,
}

// ========== A4 Passive ==========
// A4 Geo bonus - EM multipliers for 1/2/3 Hydro or Geo party members
var a4GeoEM = []float64{0.07, 0.14, 0.24}

// A4 LCrs bonus - EM multipliers for 1/2/3 Hydro or Geo party members
var a4LCrsEM = []float64{0.48, 0.96, 1.60}

// ========== C2 ==========
// C2 lamp DMG - EM scaling
var c2LampEM = 4.00

// C2 lamp DMG - DEF scaling
var c2LampDEF = 2.00
