id: 90000005
key: "kinich"
rarity: QUALITY_ORANGE
body: BODY_BOY
region: ASSOC_TYPE_NATLAN
element: Grass
weapon_class: WEAPON_CLAYMORE
icon_name: "UI_AvatarIcon_Ambor"
stats: {
   base_hp: 1001
   base_atk: 26
   base_def: 62
   hp_curve: GROW_CURVE_HP_S5
   atk_curve: GROW_CURVE_ATTACK_S5
   def_cruve: GROW_CURVE_HP_S5
   promo_data: {
      max_level: 20
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
      }
   }
   promo_data: {
      max_level: 40
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 858
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 53
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
         value: 22
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
      }
   }
   promo_data: {
      max_level: 50
add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1467.609
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 90.6565
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 37.631
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
         value: 0.096
      }
   }
   promo_data: {
      max_level: 60
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2280.4782
      }
add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 140.8687
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 58.4738
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
         value: 0.192
      }
   }
   promo_data: {
      max_level: 70
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2890.0872
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 178.5252
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 74.1048
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
         value: 0.192
      }
   }
   promo_data: {
      max_level: 80
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3499.6962
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 216.1817
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 89.7358
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
         value: 0.288
      }
   }
   promo_data: {
      max_level: 90
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 4109.391
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 253.8435
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 105.369
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
         value: 0.384
      }
   }
}
skill_details: {
   skill: 10262
   burst: 10265
   attack: 10261
   burst_energy_cost: 70
}
name_text_hash_map: 1021947691