id: 90000005
key: "kinich"
rarity: QUALITY_ORANGE
body: BODY_BOY
region: ASSOC_TYPE_RANGER
element: Grass
weapon_class: WEAPON_CLAYMORE
icon_name: "UI_AvatarIcon_Ambor"
stats: {
   base_hp: 1001
   base_atk: 26
   base_def: 62
   hp_curve: GROW_CURVE_HP_S5
   atk_curve: GROW_CURVE_ATTACK_S5
   def_cruve: GROW_CURVE_HP_S5
   promo_data: {
      max_level: 20
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
      }
   }
   promo_data: {
      max_level: 40
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1001
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 62
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
         value: 26
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
      }
   }
   promo_data: {
      max_level: 50
add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1712.23684210526
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 106.052631578947
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 44.4736842105263
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
         value: 0.096
      }
   }
   promo_data: {
      max_level: 60
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2660.55263157895
      }
add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 164.789473684211
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 69.1052631578947
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
         value: 0.192
      }
   }
   promo_data: {
      max_level: 70
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3371.78912378808
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 208.84208359127
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 87.5789382802098
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
         value: 0.192
      }
   }
   promo_data: {
      max_level: 80
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 4083.02614084141
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 252.894726006161
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 106.052627034842
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
         value: 0.288
      }
   }
   promo_data: {
      max_level: 90
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 4794.26315789474
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 296.947368421053
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 124.526315789474
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
         value: 0.384
      }
   }
}
skill_details: {
   skill: 10262
   burst: 10265
   attack: 10261
   burst_energy_cost: 70
}
name_text_hash_map: 1021947691
