// Code generated by "pipeline"; DO NOT EDIT.
package kinich

import (
	_ "embed"

	"fmt"
	"slices"

	"github.com/genshinsim/gcsim/pkg/core/action"
	"github.com/genshinsim/gcsim/pkg/core/keys"
	"github.com/genshinsim/gcsim/pkg/gcs/validation"
	"github.com/genshinsim/gcsim/pkg/model"
	"google.golang.org/protobuf/encoding/prototext"
)

//go:embed data_gen.textproto
var pbData []byte
var base *model.AvatarData
var paramKeysValidation = map[action.Action][]string{
	1: {"travel","hold"},
	3: {"blindspot"},
	8: {"blindspot"},
	11: {"blindspot"},
}

func init() {
	base = &model.AvatarData{}
	err := prototext.Unmarshal(pbData, base)
	if err != nil {
		panic(err)
	}
	validation.RegisterCharParamValidationFunc(keys.Kinich, ValidateParamKeys)
}

func ValidateParamKeys(a action.Action, keys []string) error {
	valid, ok := paramKeysValidation[a]
	if !ok {
		return nil
	}
	for _, v := range keys {
		if !slices.Contains(valid, v) {
			return fmt.Errorf("key %v is invalid for action %v", v, a.String())
		}
	}
	return nil
}

func (x *char) Data() *model.AvatarData {
	return base
}

var (
	attack = [][]float64{
		attack_1,
		attack_2,
		attack_3,
	}
)

var (
	// attack: attack_1 = [0]
	attack_1 = []float64{
		0.99,
		1.07019,
		1.15137,
		1.26621,
		1.3464,
		1.43847,
		1.56519,
		1.69191,
		1.81863,
		1.95723,
		2.09484,
		2.23344,
		2.37105,
		2.37105,
		2.37105,
	}
	// attack: attack_2 = [1]
	attack_2 = []float64{
		0.829,
		0.896149,
		0.964127,
		1.060291,
		1.12744,
		1.204537,
		1.310649,
		1.416761,
		1.522873,
		1.638933,
		1.754164,
		1.870224,
		1.985455,
		1.985455,
		1.985455,
	}
	// attack: attack_3 = [2]
	attack_3 = []float64{
		1.235,
		1.335035,
		1.436305,
		1.579565,
		1.6796,
		1.794455,
		1.952535,
		2.110615,
		2.268695,
		2.441595,
		2.61326,
		2.78616,
		2.957825,
		2.957825,
		2.957825,
	}
	// skill: skillNA = [0]
	skillNA = []float64{
		0.573,
		0.615975,
		0.65895,
		0.71625,
		0.759225,
		0.8022,
		0.8595,
		0.9168,
		0.9741,
		1.0314,
		1.0887,
		1.146,
		1.217625,
		1.217625,
		1.217625,
	}
	// skill: skillSSC = [1]
	skillSSC = []float64{
		6.874,
		7.38955,
		7.9051,
		8.5925,
		9.10805,
		9.6236,
		10.311,
		10.9984,
		11.6858,
		12.3732,
		13.0606,
		13.748,
		14.60725,
		14.60725,
		14.60725,
	}
	// burst: burst = [0]
	burst = []float64{
		1.34,
		1.4405,
		1.541,
		1.675,
		1.7755,
		1.876,
		2.01,
		2.144,
		2.278,
		2.412,
		2.546,
		2.68,
		2.8475,
		2.8475,
		2.8475,
	}
	// burst: burstDot = [1]
	burstDot = []float64{
		1.207,
		1.297525,
		1.38805,
		1.50875,
		1.599275,
		1.6898,
		1.8105,
		1.9312,
		2.0519,
		2.1726,
		2.2933,
		2.414,
		2.564875,
		2.564875,
		2.564875,
	}
)
