package_name: kachina
genshin_id: 90000000
key: kachina
action_param_keys:
  skill:
    - param: "hold"
skill_data_mapping:
  attack:
    attack_1:
      - 0 # 1-Hit DMG|{param0:F1P}
    attack_2:
      - 1 # 2-Hit DMG 1|{param1:F1P}
      - 2 # 2-Hit DMG 2|{param2:F1P}
    attack_3:
      - 3 # 3-Hit DMG|{param3:F1P}
    attack_4:
      - 4 # 4-Hit DMG|{param4:F1P}
    charge:
      - 5 # Charged Attack DMG|{param5:F1P}
  skill:
    skillRide:
      - 0 # Turbo Twirly Mounted DMG|{param0:F1P}
    skillIndependent:
      - 2 # Turbo Twirly Independent DMG|{param1:F1P}
  burst:
    burst:
      - 0 # Skill DMG|{param0:F1P}