id: 90000001
key: "mualani"
rarity: QUALITY_ORANGE
body: BODY_GIRL
region: ASSOC_TYPE_NATLAN
element: Water
weapon_class: WEAPON_CATALYST
icon_name: "UI_AvatarIcon_Ambor"
stats: {
   base_hp: 1182
   base_atk: 14
   base_def: 44
   hp_curve: GROW_CURVE_HP_S5
   atk_curve: GROW_CURVE_ATTACK_S5
   def_cruve: GROW_CURVE_HP_S5
   promo_data: {
      max_level: 20
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
      }
   }
   promo_data: {
      max_level: 40
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1182
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 44
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 14
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
      }
   }
   promo_data: {
      max_level: 50
add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2021.84210526316
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 75.2631578947368
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 23.9473684210526
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.048
      }
   }
   promo_data: {
      max_level: 60
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3141.63157894737
      }
add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 116.947368421053
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 37.2105263157895
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.096
      }
   }
   promo_data: {
      max_level: 70
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3981.47327104646
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 148.21051093574
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 47.1578898431899
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.096
      }
   }
   promo_data: {
      max_level: 80
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 4821.31558289165
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 179.473676520501
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 57.1052607110686
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.144
      }
   }
   promo_data: {
      max_level: 90
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 5661.15789473684
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 210.736842105263
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 67.0526315789474
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.192
      }
   }
}
skill_details: {
   skill: 10262
   burst: 10265
   attack: 10261
   burst_energy_cost: 60
}
name_text_hash_map: 1021947691