id: 90000001
key: "mualani"
rarity: QUALITY_ORANGE
body: BODY_GIRL
region: ASSOC_TYPE_NATLAN
element: Water
weapon_class: WEAPON_CATALYST
icon_name: "UI_AvatarIcon_Ambor"
stats: {
   base_hp: 1182
   base_atk: 14
   base_def: 44
   hp_curve: GROW_CURVE_HP_S5
   atk_curve: GROW_CURVE_ATTACK_S5
   def_cruve: GROW_CURVE_HP_S5
   promo_data: {
      max_level: 20
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
      }
   }
   promo_data: {
      max_level: 40
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1014
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 38
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 22
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
      }
   }
   promo_data: {
      max_level: 50
add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1734.447
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 64.999
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 37.631
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.048
      }
   }
   promo_data: {
      max_level: 60
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2695.1106
      }
add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 101.0002
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 58.4738
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.096
      }
   }
   promo_data: {
      max_level: 70
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3415.5576
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 127.9992
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 74.1048
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.096
      }
   }
   promo_data: {
      max_level: 80
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 4136.0046
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 154.9982
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 89.7358
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.144
      }
   }
   promo_data: {
      max_level: 90
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 4856.553
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 182.001
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 105.369
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.192
      }
   }
}
skill_details: {
   skill: 10262
   burst: 10265
   attack: 10261
   burst_energy_cost: 60
}
name_text_hash_map: 1021947691