package nefer

import (
	"github.com/genshinsim/gcsim/pkg/core/attributes"
	"github.com/genshinsim/gcsim/pkg/core/combat"
	"github.com/genshinsim/gcsim/pkg/core/player/character"
	"github.com/genshinsim/gcsim/pkg/modifier"
)

// A0
// Every point of Elemental Mastery that Lauma has increasing Lunar-Bloom's Base DMG by 0.0175%, up to a maximum of 14%.
func (c *char) a0() {
	for _, char := range c.Core.Player.Chars() {
		char.AddStatus("LB-Key", -1, false)
		char.AddLBBaseReactBonusMod(character.LBBaseReactBonusMod{
			Base: modifier.NewBase("Moonsign Benediction: Dusklit Eaves (A0)", -1),
			Amount: func(ai combat.AttackInfo) (float64, bool) {
				maxval := 0.14
				return min(maxval, c.Stat(attributes.EM)*0.000175), false
			},
		})
	}
}

// A1
/*
When the moonsign is Moonsign: Ascendant Gleam, using Nefer's Elemental Skill makes every Dendro Cores and Bountiful Cores on the field will be converted to "Seeds of Deceit".
simultaneously, Nefer gives the "Deceit" state to every party member for 15s. When the party member is in this state, every Dendro Cores and Bountiful Core generated by them will be converted into Seeds of Deceit instantly, and Hyperbloom or Burgeon reactions will be blocked.

When Nefer unleashes a Charged Attack or Phantasm Performance, she can absorb Seeds of Deceit on the field, gaining 1 stack of Veil of Falsehood for every seed absorbed.
When this effect reaches 3 stacks, or when the third stack's duration is refreshed, Nefer's Elemental Mastery will be increased by 100 for 8s.

Veil of Falsehood
Increases the DMG dealt by her Phantasm Performance.
Each stack of Veil of Falsehood increases the DMG dealt by Nefer's Phantasm Performance by 8%.
The initial maximum number of stacks is 3, with each stack lasting for 9s (each stack's duration is counted independently).

TO COPILOT: this buff is not conventional one, and has a special calculation method. for now, use c.a1buff as a value holder.
*/
func (c *char) a1() {
	if c.Base.Ascension < 1 {
		return
	}
	// Placeholder for A1 passive implementation
}
