// Code generated by "pipeline"; DO NOT EDIT.
package nefer

import (
	_ "embed"

	"fmt"
	"slices"

	"github.com/Karashina/gcsim-unofficial-clone/pkg/core/action"
	"github.com/Karashina/gcsim-unofficial-clone/pkg/core/keys"
	"github.com/Karashina/gcsim-unofficial-clone/pkg/gcs/validation"
	"github.com/Karashina/gcsim-unofficial-clone/pkg/model"
	"google.golang.org/protobuf/encoding/prototext"
)

//go:embed data_gen.textproto
var pbData []byte
var base *model.AvatarData
var paramKeysValidation = map[action.Action][]string{
	4: {"hold"},
	5: {"collision"},
	6: {"collision"},
}

func init() {
	base = &model.AvatarData{}
	err := prototext.Unmarshal(pbData, base)
	if err != nil {
		panic(err)
	}
	validation.RegisterCharParamValidationFunc(keys.Nefer, ValidateParamKeys)
}

func ValidateParamKeys(a action.Action, keys []string) error {
	valid, ok := paramKeysValidation[a]
	if !ok {
		return nil
	}
	for _, v := range keys {
		if !slices.Contains(valid, v) {
			return fmt.Errorf("key %v is invalid for action %v", v, a.String())
		}
	}
	return nil
}

func (x *char) Data() *model.AvatarData { return base }

// Talent scaling tables (generated from data_gen.textproto)
var (
	attack = [][][]float64{{attack_1}, {attack_2}, {attack_3, attack_3}, {attack_4}}

	attack_1 = []float64{0.381, 0.409, 0.438, 0.476, 0.504, 0.533, 0.571, 0.609, 0.647, 0.685, 0.723, 0.723, 0.723, 0.723, 0.723}
	attack_2 = []float64{0.376, 0.404, 0.432, 0.47, 0.498, 0.526, 0.563, 0.601, 0.639, 0.676, 0.714, 0.714, 0.714, 0.714, 0.714}
	attack_3 = []float64{0.252, 0.271, 0.29, 0.316, 0.334, 0.353, 0.379, 0.404, 0.429, 0.454, 0.48, 0.48, 0.48, 0.48, 0.48}
	attack_4 = []float64{0.61, 0.656, 0.701, 0.762, 0.808, 0.854, 0.915, 0.976, 1.037, 1.098, 1.159, 1.159, 1.159, 1.159, 1.159}

	charge     = []float64{1.309, 1.407, 1.505, 1.636, 1.734, 1.832, 1.963, 2.094, 2.225, 2.356, 2.487, 2.487, 2.487, 2.487, 2.487}
	collision  = []float64{0.568, 0.615, 0.661, 0.727, 0.773, 0.826, 0.899, 0.971, 1.044, 1.123, 1.203, 1.203, 1.203, 1.203, 1.203}
	highPlunge = []float64{1.42, 1.53, 1.65, 1.82, 1.93, 2.06, 2.24, 2.43, 2.61, 2.81, 3.0, 3.0, 3.0, 3.0, 3.0}
	lowPlunge  = []float64{1.14, 1.23, 1.32, 1.45, 1.55, 1.65, 1.8, 1.94, 2.09, 2.25, 2.4, 2.4, 2.4, 2.4, 2.4}

	skillatk = []float64{0.764, 0.821, 0.878, 0.955, 1.012, 1.069, 1.146, 1.222, 1.299, 1.375, 1.451, 1.528, 1.623}
	skillem  = []float64{1.528, 1.642, 1.757, 1.91, 2.024, 2.139, 2.292, 2.444, 2.597, 2.75, 2.903, 3.055, 3.246}

	skillppn1atk = []float64{0.246, 0.265, 0.283, 0.308, 0.326, 0.345, 0.37, 0.394, 0.419, 0.444, 0.468, 0.493, 0.524}
	skillppn1em  = []float64{0.493, 0.53, 0.567, 0.616, 0.653, 0.69, 0.739, 0.788, 0.838, 0.887, 0.936, 0.986, 1.047}
	skillppn2atk = []float64{0.32, 0.344, 0.368, 0.4, 0.424, 0.448, 0.48, 0.513, 0.545, 0.577, 0.609, 0.641, 0.681}
	skillppn2em  = []float64{0.641, 0.689, 0.737, 0.801, 0.849, 0.897, 0.961, 1.025, 1.089, 1.153, 1.217, 1.281, 1.361}
	skillpps1    = []float64{0.96, 1.032, 1.104, 1.2, 1.272, 1.344, 1.44, 1.536, 1.632, 1.728, 1.824, 1.92, 2.04}
	skillpps2    = []float64{0.96, 1.032, 1.104, 1.2, 1.272, 1.344, 1.44, 1.536, 1.632, 1.728, 1.824, 1.92, 2.04}
	skillpps3    = []float64{1.28, 1.376, 1.472, 1.6, 1.696, 1.792, 1.92, 2.048, 2.176, 2.304, 2.432, 2.56, 2.72}

	burst1atk  = []float64{2.246, 2.415, 2.583, 2.808, 2.976, 3.145, 3.37, 3.594, 3.819, 4.044, 4.268, 4.493, 4.774}
	burst1em   = []float64{4.493, 4.83, 5.167, 5.616, 5.953, 6.29, 6.739, 7.188, 7.638, 8.087, 8.536, 8.986, 9.547}
	burst2atk  = []float64{3.37, 3.622, 3.875, 4.212, 4.465, 4.717, 5.054, 5.391, 5.728, 6.065, 6.402, 6.739, 7.16}
	burst2em   = []float64{6.739, 7.245, 7.75, 8.424, 8.929, 9.435, 10.109, 10.783, 11.457, 12.131, 12.804, 13.478, 14.321}
	burstbonus = []float64{0.13, 0.16, 0.19, 0.22, 0.25, 0.28, 0.31, 0.34, 0.37, 0.4, 0.43, 0.46, 0.49}
)
