id: 90641
key: "zibai"
rarity: QUALITY_ORANGE
body: BODY_LADY
region: ASSOC_TYPE_LIYUE
element: Rock
weapon_class: WEAPON_SWORD_ONE_HAND
icon_name: "UI_AvatarIcon_Zibai"
stats: {
   base_hp: 1006.0
   base_atk: 17.0
   base_def: 74.0
   hp_curve: GROW_CURVE_HP_S5
   atk_curve: GROW_CURVE_ATTACK_S5
   def_cruve: GROW_CURVE_HP_S5
   promo_data: {
      max_level: 20
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
      }
   }
   promo_data: {
      max_level: 40
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 862.0
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 65.0
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 16.0
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
      }
   }
   promo_data: {
      max_level: 50
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2272.0
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 66.0
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 17.0
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
         value: 0.096
      }
   }
   promo_data: {
      max_level: 60
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2291.0
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 172.5
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 42.5
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
         value: 0.192
      }
   }
   promo_data: {
      max_level: 70
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2904.0
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 218.0
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 54.0
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
         value: 0.192
      }
   }
   promo_data: {
      max_level: 80
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3515.5
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 263.5
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 65.0
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
         value: 0.288
      }
   }
   promo_data: {
      max_level: 90
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 4128.0
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 310.0
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 76.0
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
         value: 0.384
      }
   }
}
skill_details: {
   skill: 90641002
   burst: 90641003
   attack: 90641001
   burst_energy_cost: 60
}
