// Code generated by "pipeline"; DO NOT EDIT.
package zibai

import (
	_ "embed"

	"github.com/Karashina/gcsim-unofficial-clone/pkg/model"
	"google.golang.org/protobuf/encoding/prototext"
)

//go:embed data_gen.textproto
var pbData []byte
var base *model.AvatarData

func init() {
	base = &model.AvatarData{}
	err := prototext.Unmarshal(pbData, base)
	if err != nil {
		panic(err)
	}
}

func (x *char) Data() *model.AvatarData {
	return base
}

var (
	attack = [][][]float64{
		{attack_1},
		{attack_2},
		{attack_3_1, attack_3_2},
		{attack_4},
	}
	lunarPhaseShiftAttack = [][][]float64{
		{lunarPhaseShift_1},
		{lunarPhaseShift_2},
		{lunarPhaseShift_3_1, lunarPhaseShift_3_2},
		{lunarPhaseShift_4},
	}
)

// Normal Attack 1-Hit DMG (15 entries)
var attack_1 = []float64{
	0.506, 0.547, 0.588, 0.647, 0.688, 0.735, 0.799, 0.864, 0.929, 0.999,
	1.070, 1.070, 1.070, 1.070, 1.070,
}

// Normal Attack 2-Hit DMG (15 entries)
var attack_2 = []float64{
	0.466, 0.503, 0.541, 0.595, 0.633, 0.677, 0.736, 0.796, 0.855, 0.920,
	0.985, 0.985, 0.985, 0.985, 0.985,
}

// Normal Attack 3-Hit DMG part 1 (15 entries)
var attack_3_1 = []float64{
	0.309, 0.334, 0.359, 0.395, 0.420, 0.449, 0.488, 0.528, 0.567, 0.611,
	0.654, 0.654, 0.654, 0.654, 0.654,
}

// Normal Attack 3-Hit DMG part 2 (15 entries)
var attack_3_2 = []float64{
	0.309, 0.334, 0.359, 0.395, 0.420, 0.449, 0.488, 0.528, 0.567, 0.611,
	0.654, 0.654, 0.654, 0.654, 0.654,
}

// Normal Attack 4-Hit DMG (15 entries)
var attack_4 = []float64{
	0.779, 0.842, 0.906, 0.996, 1.060, 1.132, 1.232, 1.331, 1.431, 1.540,
	1.648, 1.648, 1.648, 1.648, 1.648,
}

// Charged Attack DMG part 1 (15 entries)
var charge_1 = []float64{
	0.737, 0.797, 0.857, 0.942, 1.002, 1.071, 1.165, 1.259, 1.353, 1.456,
	1.559, 1.559, 1.559, 1.559, 1.559,
}

// Charged Attack DMG part 2 (15 entries)
var charge_2 = []float64{
	0.737, 0.797, 0.857, 0.942, 1.002, 1.071, 1.165, 1.259, 1.353, 1.456,
	1.559, 1.559, 1.559, 1.559, 1.559,
}

// Plunge DMG (15 entries)
var plunge = []float64{
	0.639, 0.691, 0.743, 0.818, 0.870, 0.929, 1.011, 1.093, 1.175, 1.264,
	1.353, 1.353, 1.353, 1.353, 1.353,
}

// Low Plunge DMG (15 entries)
var lowPlunge = []float64{
	1.28, 1.38, 1.49, 1.64, 1.74, 1.86, 2.02, 2.19, 2.35, 2.53,
	2.71, 2.71, 2.71, 2.71, 2.71,
}

// High Plunge DMG (15 entries)
var highPlunge = []float64{
	1.60, 1.73, 1.86, 2.04, 2.17, 2.32, 2.53, 2.73, 2.93, 3.16,
	3.38, 3.38, 3.38, 3.38, 3.38,
}

// ========== Lunar Phase Shift (DEF-scaling) ==========
// Lunar Phase Shift 1-Hit DMG (DEF %) (15 entries)
var lunarPhaseShift_1 = []float64{
	0.566, 0.608, 0.651, 0.707, 0.750, 0.792, 0.849, 0.905, 0.962, 1.018,
	1.075, 1.132, 1.202, 1.202, 1.202,
}

// Lunar Phase Shift 2-Hit DMG (DEF %) (15 entries)
var lunarPhaseShift_2 = []float64{
	0.521, 0.560, 0.599, 0.651, 0.690, 0.729, 0.782, 0.834, 0.886, 0.938,
	0.990, 1.042, 1.107, 1.107, 1.107,
}

// Lunar Phase Shift 3-Hit DMG part 1 (DEF %) (15 entries)
var lunarPhaseShift_3_1 = []float64{
	0.346, 0.372, 0.398, 0.432, 0.458, 0.484, 0.519, 0.553, 0.588, 0.622,
	0.657, 0.691, 0.735, 0.735, 0.735,
}

// Lunar Phase Shift 3-Hit DMG part 2 (DEF %) (15 entries)
var lunarPhaseShift_3_2 = []float64{
	0.346, 0.372, 0.398, 0.432, 0.458, 0.484, 0.519, 0.553, 0.588, 0.622,
	0.657, 0.691, 0.735, 0.735, 0.735,
}

// Lunar Phase Shift 4-Hit DMG (DEF %) (15 entries)
var lunarPhaseShift_4 = []float64{
	0.872, 0.937, 1.003, 1.090, 1.155, 1.221, 1.308, 1.395, 1.482, 1.569,
	1.656, 1.744, 1.853, 1.853, 1.853,
}

// Lunar Phase Shift Charged Attack DMG part 1 (DEF %) (15 entries)
var lunarPhaseShiftCharge_1 = []float64{
	0.660, 0.709, 0.758, 0.824, 0.874, 0.923, 0.989, 1.055, 1.121, 1.187,
	1.253, 1.319, 1.401, 1.401, 1.401,
}

// Lunar Phase Shift Charged Attack DMG part 2 (DEF %) (15 entries)
var lunarPhaseShiftCharge_2 = []float64{
	0.660, 0.709, 0.758, 0.824, 0.874, 0.923, 0.989, 1.055, 1.121, 1.187,
	1.253, 1.319, 1.401, 1.401, 1.401,
}

// Spirit Steed's Stride 1-Hit DMG (DEF %) (15 entries)
var spiritSteedStride_1 = []float64{
	1.725, 1.855, 1.984, 2.157, 2.286, 2.415, 2.588, 2.760, 2.933, 3.106,
	3.278, 3.451, 3.666, 3.666, 3.666,
}

// Spirit Steed's Stride 2-Hit DMG (DEF %) (15 entries)
var spiritSteedStride_2 = []float64{
	1.410, 1.515, 1.621, 1.762, 1.868, 1.974, 2.115, 2.255, 2.396, 2.537,
	2.678, 2.819, 2.996, 2.996, 2.996,
}

// Lunar Phase Shift 4-Hit Additional DMG (DEF %) (15 entries)
var lunarPhaseShift4Additional = []float64{
	0.295, 0.317, 0.339, 0.368, 0.390, 0.412, 0.442, 0.471, 0.501, 0.530,
	0.560, 0.589, 0.626, 0.626, 0.626,
}

// ========== Elemental Burst ==========
// Skill 1-Hit DMG (DEF %) (15 entries)
var burstInitial = []float64{
	1.270, 1.365, 1.460, 1.587, 1.682, 1.777, 1.904, 2.031, 2.158, 2.285,
	2.412, 2.539, 2.698, 2.698, 2.698,
}

// Skill 2-Hit DMG (DEF %) - Lunar-Crystallize (15 entries)
var burstSecond = []float64{
	1.777, 1.911, 2.044, 2.222, 2.355, 2.488, 2.666, 2.844, 3.022, 3.199,
	3.377, 3.555, 3.777, 3.777, 3.777,
}
