id: 90000004
key: "emilie"
rarity: QUALITY_ORANGE
body: BODY_GIRL
region: ASSOC_TYPE_FONTAINE
element: Grass
weapon_class: WEAPON_POLE
icon_name: "UI_AvatarIcon_Ambor"
stats: {
   base_hp: 1056
   base_atk: 26
   base_def: 57
   hp_curve: GROW_CURVE_HP_S5
   atk_curve: GROW_CURVE_ATTACK_S5
   def_cruve: GROW_CURVE_HP_S5
   promo_data: {
      max_level: 20
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
      }
   }
   promo_data: {
      max_level: 40
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1056
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 57
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
         value: 26
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
      }
   }
   promo_data: {
      max_level: 50
add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1806.31578947368
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 97.5
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 44.4736842105263
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
         value: 0.096
      }
   }
   promo_data: {
      max_level: 60
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2806.73684210526
      }
add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 151.5
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 69.1052631578947
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
         value: 0.192
      }
   }
   promo_data: {
      max_level: 70
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3557.05226245775
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 191.999980075845
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 87.5789382802098
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
         value: 0.192
      }
   }
   promo_data: {
      max_level: 80
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 4307.36823649204
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 232.499990037922
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 106.052627034842
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
         value: 0.288
      }
   }
   promo_data: {
      max_level: 90
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 5057.68421052632
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 273
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 124.526315789474
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
         value: 0.384
      }
   }
}
skill_details: {
   skill: 10262
   burst: 10265
   attack: 10261
   burst_energy_cost: 50
}
name_text_hash_map: 1021947691